#!/usr/bin/env python3
"""
setup-ai-docs.py

Builder script:
1) Reads master-prompt.md
2) Asks target OS
3) Generates a drop-in executable bootstrap file that can be copied to any project
   to create AI agent markdown documentation files.
"""

from __future__ import annotations

import json
import stat
import textwrap
from pathlib import Path


def ask_target_os() -> str:
    options = {
        "1": "macos",
        "2": "linux",
        "3": "windows",
        "4": "auto",
    }
    print("Select target OS for the generated executable:")
    print("  1) macOS")
    print("  2) Linux")
    print("  3) Windows")
    print("  4) Auto (recommended)")

    while True:
        choice = input("Enter choice [1-4] (default 4): ").strip() or "4"
        if choice in options:
            return options[choice]
        print("Invalid choice. Please select 1, 2, 3, or 4.")


def build_bootstrap_script(master_prompt: str, target_os: str) -> str:
    prompt_literal = json.dumps(master_prompt)
    target_os_literal = json.dumps(target_os)

    return textwrap.dedent(
        f'''\
#!/usr/bin/env python3
"""
Drop-in executable generated by setup-ai-docs.py.
Run this file inside any project repository to generate AI agent markdown docs.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except Exception:  # pragma: no cover
    tomllib = None

MASTER_PROMPT = {prompt_literal}
GENERATOR_TARGET_OS = {target_os_literal}
GENERATOR_VERSION = "1.0.0"

DEFAULT_AGENTS = [
    "cursor",
    "github-copilot",
    "claude-code",
    "openai-codex",
    "antigravity",
]

STACK_PRESETS = {{
    "react-ts": {{
        "languages": ["TypeScript"],
        "frameworks": ["React"],
        "tests": ["vitest", "@testing-library/react"],
        "linting": ["eslint", "prettier"],
        "suggestions": [
            "Enable strict tsconfig and type-aware ESLint rules.",
            "Use Testing Library with Vitest for component and integration tests.",
        ],
    }},
    "next-ts": {{
        "languages": ["TypeScript"],
        "frameworks": ["Next.js"],
        "tests": ["vitest", "playwright"],
        "linting": ["eslint", "prettier"],
        "suggestions": [
            "Adopt route-level testing and API contract checks.",
            "Use preview deployments to validate doc-guided workflows.",
        ],
    }},
    "node-api": {{
        "languages": ["TypeScript"],
        "frameworks": ["Express"],
        "tests": ["vitest", "supertest"],
        "linting": ["eslint", "prettier"],
        "suggestions": [
            "Validate request/response schemas at boundaries.",
            "Add integration tests for critical API paths.",
        ],
    }},
    "fastapi": {{
        "languages": ["Python"],
        "frameworks": ["FastAPI"],
        "tests": ["pytest"],
        "linting": ["ruff", "mypy"],
        "suggestions": [
            "Use pydantic models for strict input/output validation.",
            "Add contract tests for OpenAPI schema compatibility.",
        ],
    }},
}}


def now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def hash_text(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def detect_project_type(project_dir: Path) -> str:
    manifest_candidates = [
        "package.json",
        "pyproject.toml",
        "requirements.txt",
        "go.mod",
        "Cargo.toml",
        "pom.xml",
        "build.gradle",
        "Gemfile",
    ]
    has_manifest = any((project_dir / name).exists() for name in manifest_candidates)
    has_source = any((project_dir / d).exists() for d in ["src", "app", "services", "backend", "frontend"])
    has_docs = any(project_dir.glob("*.md"))
    return "existing" if (has_manifest or has_source or has_docs) else "new"


def read_json_file(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {{}}


def parse_requirements_txt(path: Path) -> list[str]:
    deps = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        dep = re.split(r"[<>=~! ]", line, maxsplit=1)[0].strip()
        if dep:
            deps.append(dep)
    return deps


def parse_toml_dependencies(path: Path) -> list[str]:
    if not tomllib:
        return []
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []

    deps = []
    project = data.get("project", {{}})
    for dep in project.get("dependencies", []) or []:
        dep_name = re.split(r"[<>=~! ]", dep, maxsplit=1)[0].strip()
        if dep_name:
            deps.append(dep_name)

    poetry = data.get("tool", {{}}).get("poetry", {{}})
    poetry_deps = poetry.get("dependencies", {{}})
    for name in poetry_deps:
        if name.lower() != "python":
            deps.append(name)

    return sorted(set(deps))


def detect_stack(project_dir: Path) -> dict:
    languages = set()
    frameworks = set()
    package_managers = set()
    packages = set()
    scripts = {{}}

    package_json = project_dir / "package.json"
    if package_json.exists():
        languages.update(["JavaScript", "TypeScript"])
        package_managers.add("npm/pnpm/yarn")
        data = read_json_file(package_json)
        deps = data.get("dependencies", {{}})
        dev_deps = data.get("devDependencies", {{}})
        all_deps = {{**deps, **dev_deps}}
        packages.update(all_deps.keys())
        scripts = data.get("scripts", {{}})

        framework_map = {{
            "react": "React",
            "next": "Next.js",
            "vue": "Vue",
            "nuxt": "Nuxt",
            "svelte": "Svelte",
            "angular": "Angular",
            "express": "Express",
            "nestjs": "NestJS",
            "fastify": "Fastify",
        }}
        for dep_name, fw in framework_map.items():
            if dep_name in all_deps:
                frameworks.add(fw)

    pyproject = project_dir / "pyproject.toml"
    requirements = project_dir / "requirements.txt"
    if pyproject.exists() or requirements.exists():
        languages.add("Python")
        package_managers.add("pip/poetry")
        if pyproject.exists():
            packages.update(parse_toml_dependencies(pyproject))
        if requirements.exists():
            packages.update(parse_requirements_txt(requirements))

        py_framework_map = {{
            "fastapi": "FastAPI",
            "django": "Django",
            "flask": "Flask",
            "pydantic": "Pydantic",
        }}
        pkg_lower = {{p.lower() for p in packages}}
        for dep_name, fw in py_framework_map.items():
            if dep_name in pkg_lower:
                frameworks.add(fw)

    if (project_dir / "go.mod").exists():
        languages.add("Go")
        package_managers.add("go modules")

    if (project_dir / "Cargo.toml").exists():
        languages.add("Rust")
        package_managers.add("cargo")

    if list(project_dir.glob("*.csproj")):
        languages.add("C#")
        package_managers.add("nuget")

    if (project_dir / "pom.xml").exists() or (project_dir / "build.gradle").exists():
        languages.add("Java")
        package_managers.add("maven/gradle")

    if (project_dir / "Gemfile").exists():
        languages.add("Ruby")
        package_managers.add("bundler")

    return {{
        "languages": sorted(languages),
        "frameworks": sorted(frameworks),
        "package_managers": sorted(package_managers),
        "packages": sorted(packages),
        "scripts": scripts,
    }}


def gather_existing_markdown_context(project_dir: Path, max_files: int = 20) -> list[dict]:
    generated_roots = {
            (
                "AGENTS.md",
                "AI_DOCS_INDEX.md",
                "CLAUDE.md",
                "CODEX.md",
                "ANTIGRAVITY.md",
            )
        }
    docs = []
    for md_file in sorted(project_dir.rglob("*.md")):
        rel = md_file.relative_to(project_dir).as_posix()
        if rel.startswith(".git/"):
            continue
        if rel.startswith(".ai-docs/"):
            continue
        if rel.startswith(".github/") or rel.startswith(".cursor/"):
            continue
        if rel in generated_roots:
            continue
        try:
            content = md_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        docs.append({{"path": rel, "preview": content[:500].strip()}})
        if len(docs) >= max_files:
            break
    return docs


def merge_unique(existing: list[str], incoming: list[str]) -> list[str]:
    merged = []
    seen = set()
    for item in (existing or []) + (incoming or []):
        value = item.strip()
        if not value:
            continue
        key = value.lower()
        if key in seen:
            continue
        seen.add(key)
        merged.append(value)
    return merged


def ask_new_project_details() -> dict:
    print("\\nDetected a NEW project. Please provide setup details.")
    print("Available stack presets: react-ts, next-ts, node-api, fastapi")

    os_value = input("Target OS (macos/linux/windows, default auto): ").strip().lower() or "auto"
    preset = input("Stack preset (optional, press Enter to skip): ").strip().lower()
    agents_raw = input(
        "Agents (comma separated, default: cursor,github-copilot,claude-code,openai-codex,antigravity): "
    ).strip()
    lang_raw = input("Languages (comma separated, e.g. TypeScript,Python): ").strip()
    fw_raw = input("Frameworks (comma separated, e.g. React,FastAPI): ").strip()
    test_raw = input("Testing tools (comma separated, e.g. vitest,pytest): ").strip()
    lint_raw = input("Lint/format tools (comma separated, e.g. eslint,prettier,ruff): ").strip()

    agents = [a.strip() for a in agents_raw.split(",") if a.strip()] if agents_raw else list(DEFAULT_AGENTS)
    languages = [l.strip() for l in lang_raw.split(",") if l.strip()]
    frameworks = [f.strip() for f in fw_raw.split(",") if f.strip()]
    tests = [t.strip() for t in test_raw.split(",") if t.strip()]
    linting = [l.strip() for l in lint_raw.split(",") if l.strip()]

    preset_data = STACK_PRESETS.get(preset, {{}})
    if preset and not preset_data:
        print(f"Unknown preset '{{preset}}'. Continuing without preset.")

    languages = merge_unique(preset_data.get("languages", []), languages)
    frameworks = merge_unique(preset_data.get("frameworks", []), frameworks)
    tests = merge_unique(preset_data.get("tests", []), tests)
    linting = merge_unique(preset_data.get("linting", []), linting)

    suggestions = []
    suggestions.extend(preset_data.get("suggestions", []))
    lset = {{x.lower() for x in languages}}
    fset = {{x.lower() for x in frameworks}}

    if "typescript" in lset and "react" in fset:
        suggestions.append("Use eslint + prettier + type-aware strict tsconfig.")
        suggestions.append("Prefer vitest + testing-library for unit/integration tests.")
    if "python" in lset:
        suggestions.append("Use ruff + mypy + pytest with pre-commit hooks.")
    if "fastapi" in fset:
        suggestions.append("Add pydantic validation and contract tests for API schemas.")

    return {{
        "target_os": os_value,
        "preset": preset,
        "agents": agents,
        "languages": languages,
        "frameworks": frameworks,
        "tests": tests,
        "linting": linting,
        "suggestions": suggestions,
    }}


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def write_text(path: Path, content: str) -> None:
    ensure_dir(path.parent)
    path.write_text(content.rstrip() + "\\n", encoding="utf-8")


def read_text_if_exists(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""


def normalize_text(content: str) -> str:
    return content.rstrip() + "\\n"


def load_previous_metadata(project_dir: Path) -> dict:
    metadata_path = project_dir / ".ai-docs" / "metadata.json"
    if not metadata_path.exists():
        return {{}}
    try:
        return json.loads(metadata_path.read_text(encoding="utf-8", errors="ignore"))
    except Exception:
        return {{}}


def list_signature(values: list[str] | None) -> list[str]:
    return sorted((values or []), key=lambda item: item.lower())


def detect_scope_changes(previous: dict, ctx: dict) -> tuple[bool, bool, bool]:
    old_stack = previous.get("stack", {{}})
    new_stack = ctx.get("stack", {{}})
    stack_changed = any(
        list_signature(old_stack.get(key)) != list_signature(new_stack.get(key))
        for key in ["languages", "frameworks", "package_managers"]
    )

    agents_changed = list_signature(previous.get("agents")) != list_signature(ctx.get("agents"))
    prompt_changed = previous.get("master_prompt_sha256") != hash_text(MASTER_PROMPT)
    return stack_changed, agents_changed, prompt_changed


def determine_impacted_files(
    project_dir: Path,
    ctx: dict,
    all_files: dict[str, str],
    agent_files: dict[str, str],
    check_mode: bool,
) -> tuple[set[str], bool, bool, bool]:
    if check_mode:
        return set(all_files.keys()), True, True, True

    previous = load_previous_metadata(project_dir)
    if not previous:
        return set(all_files.keys()), True, True, True

    stack_changed, agents_changed, prompt_changed = detect_scope_changes(previous, ctx)
    impacted = {{".ai-docs/CONTEXT-SNAPSHOT.md"}}

    if stack_changed:
        impacted = set(all_files.keys())
    else:
        if agents_changed:
            impacted.update(agent_files.keys())
            impacted.update({{"AGENTS.md", "AI_DOCS_INDEX.md"}})
        if prompt_changed:
            impacted.add(".ai-docs/MASTER_PROMPT_REFERENCE.md")

    return impacted, stack_changed, agents_changed, prompt_changed


def is_managed_generated_file(path: str) -> bool:
    managed_roots = {{
        "AGENTS.md",
        "AI_DOCS_INDEX.md",
        "CLAUDE.md",
        "CODEX.md",
        "ANTIGRAVITY.md",
        ".cursor/rules/project.mdc",
        ".github/copilot-instructions.md",
    }}
    if path in managed_roots:
        return True
    if path.startswith(".ai-docs/"):
        return True
    return False


CUSTOM_BLOCK_RE = re.compile(
    r"<!--\\s*user-custom:start(?::(?P<id>[A-Za-z0-9_.-]+))?\\s*-->.*?<!--\\s*user-custom:end(?:[:][A-Za-z0-9_.-]+)?\\s*-->",
    re.DOTALL,
)


def extract_custom_blocks(content: str) -> dict[str, str]:
    blocks = {{}}
    index = 0
    for match in CUSTOM_BLOCK_RE.finditer(content or ""):
        index += 1
        block = match.group(0)
        block_id = match.group("id") or f"block_{{index}}"
        blocks[block_id] = block
    return blocks


def ensure_default_custom_block(content: str) -> str:
    if "<!-- user-custom:start" in content:
        return content
    return (
        content.rstrip()
        + "\\n\\n<!-- user-custom:start:local -->\\n"
        + "# Add project-specific guidance here.\\n"
        + "<!-- user-custom:end:local -->\\n"
    )


def preserve_user_custom_blocks(existing_content: str, new_content: str) -> str:
    merged = ensure_default_custom_block(new_content)
    existing_blocks = extract_custom_blocks(existing_content)
    new_blocks = extract_custom_blocks(merged)

    preserved_unmatched = []
    for block_id, existing_block in existing_blocks.items():
        if block_id in new_blocks:
            merged = merged.replace(new_blocks[block_id], existing_block, 1)
        else:
            preserved_unmatched.append(existing_block)

    if preserved_unmatched:
        merged = merged.rstrip() + "\\n\\n## Preserved User Customizations\\n\\n" + "\\n\\n".join(preserved_unmatched) + "\\n"

    return merged


def resolve_generated_at(project_dir: Path, check_mode: bool) -> str:
    if not check_mode:
        return now_utc()

    metadata_path = project_dir / ".ai-docs" / "metadata.json"
    if metadata_path.exists():
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8", errors="ignore"))
            value = metadata.get("generated_at")
            if isinstance(value, str) and value.strip():
                return value.strip()
        except Exception:
            pass

    return now_utc()


def build_common_context(project_type: str, stack: dict, new_details: dict | None, generated_at: str) -> dict:
    agents = list(DEFAULT_AGENTS)
    target_os = GENERATOR_TARGET_OS if GENERATOR_TARGET_OS != "auto" else "auto"

    if new_details:
        agents = new_details.get("agents") or agents
        target_os = new_details.get("target_os") or target_os

    return {{
        "project_type": project_type,
        "target_os": target_os,
        "agents": agents,
        "stack": stack,
        "new_details": new_details or {{}},
        "generated_at": generated_at,
    }}


def generate_agents_md(ctx: dict) -> str:
    stack = ctx["stack"]
    langs = ", ".join(stack.get("languages") or ["TBD"])
    fws = ", ".join(stack.get("frameworks") or ["TBD"])

    return f"""# AGENTS.md

Last updated: {{ctx['generated_at']}}

## Purpose
Canonical cross-agent guidance for AI-assisted development in this repository.

## Project Context
- Project type: {{ctx['project_type']}}
- Target OS: {{ctx['target_os']}}
- Languages: {{langs}}
- Frameworks: {{fws}}

## Core Engineering Rules
1. Preserve existing architecture and coding style unless change is requested.
2. Write or update tests for behavior changes.
3. Prefer small, reviewable diffs.
4. Avoid exposing secrets in code, docs, or logs.
5. Document assumptions and unknowns explicitly.

## Quality Gate
- Build passes
- Lint passes
- Tests pass
- Docs updated for behavior/interface changes

## Security Gate
- No embedded credentials or tokens
- Validate inputs at boundaries
- Apply least-privilege defaults

## Spec-Driven Development
Use docs as executable intent:
- Requirements and acceptance criteria first
- Tests mapped to acceptance criteria
- Implementation follows validated tests

## Token/Context Efficiency
- Read only necessary files first, then expand.
- Summarize large contexts before synthesis.
- Reuse canonical rules from this file in agent-specific docs.

## Update Policy
- Refresh docs when stack/tooling changes.
- Record updates in .ai-docs/CHANGELOG.md.
"""


def generate_index_md(ctx: dict, files: list[str]) -> str:
    links = "\\n".join(f"- {{name}}" for name in files)
    return f"""# AI_DOCS_INDEX.md

Last updated: {{ctx['generated_at']}}

## What This Is
Entry point for AI-agent documentation in this repository.

## Generated Files
{{links}}

## Workflow
1. Run the bootstrap script after major project/tooling changes.
2. Review diffs and keep custom guidance in dedicated sections.
3. Track improvements via .ai-docs/FEEDBACK.md.

## Source Prompt
This documentation was generated from an embedded master prompt aligned to modern AI engineering practices.
"""


def generate_context_snapshot(ctx: dict, markdown_context: list[dict]) -> str:
    stack = ctx["stack"]
    preview_lines = []
    for item in markdown_context[:10]:
        preview = item["preview"].replace("\\n", " ")
        preview_lines.append(f"- {{item['path']}}: {{preview[:120]}}")

    preview_text = "\\n".join(preview_lines) if preview_lines else "- No markdown files detected during scan."
    scripts = stack.get("scripts", {{}})
    scripts_text = "\\n".join(f"- {{k}}: {{v}}" for k, v in scripts.items()) if scripts else "- No scripts detected"

    return f"""# Context Snapshot

Captured at: {{ctx['generated_at']}}

## Stack Detection
- Languages: {{', '.join(stack.get('languages') or ['Unknown'])}}
- Frameworks: {{', '.join(stack.get('frameworks') or ['Unknown'])}}
- Package Managers: {{', '.join(stack.get('package_managers') or ['Unknown'])}}
- Packages Detected: {{len(stack.get('packages') or [])}}

## Build/Test/Lint Script Signals
{{scripts_text}}

## Existing Markdown Context (Preview)
{{preview_text}}
"""


def generate_agent_specific_docs(ctx: dict) -> dict[str, str]:
    stack = ctx["stack"]
    langs = ", ".join(stack.get("languages") or ["TBD"])
    tests_hint = "Run and update tests for every behavior change."

    files = {{}}
    agents = {{a.lower() for a in ctx["agents"]}}

    if "cursor" in agents:
        files[".cursor/rules/project.mdc"] = f"""---
description: Project rules for Cursor
alwaysApply: true
---
# Cursor Project Rules

- Respect AGENTS.md as source of truth.
- Keep edits focused and minimal.
- Validate with tests/lint before finalizing.
- Stack: {{langs}}
- {{tests_hint}}
"""

    if "github-copilot" in agents or "copilot" in agents:
        files[".github/copilot-instructions.md"] = f"""# GitHub Copilot Instructions

Follow AGENTS.md first.

## Repository Priorities
- Maintain architecture consistency.
- Prefer secure defaults.
- Add tests for changed behavior.
- Keep code and docs aligned.

## Stack
{{langs}}
"""

    if "claude-code" in agents or "claude" in agents:
        files["CLAUDE.md"] = f"""# Claude Code Guide

Use this repository with AGENTS.md as canonical policy.

## Must Do
- Keep patches small and reversible.
- Explain assumptions and edge cases.
- Update tests and docs with behavior changes.
- Favor deterministic and maintainable solutions.
"""

    if "openai-codex" in agents or "codex" in agents:
        files["CODEX.md"] = f"""# OpenAI Codex Guide

This project uses AGENTS.md as the unified standard.

## Codex Working Contract
- Read project context before editing.
- Prefer minimal, high-confidence diffs.
- Run available validation commands before completion.
- Document important decisions in PR/commit notes.
"""

    if "antigravity" in agents:
        files["ANTIGRAVITY.md"] = f"""# Antigravity Agent Guide

## Purpose
Agent-specific execution guidance compatible with the repository standards in AGENTS.md.

## Operating Rules
- Preserve coding conventions and architecture.
- Keep generated output deterministic and review-friendly.
- Pair code changes with tests and concise documentation updates.
"""

    return files


def append_changelog(changelog_path: Path, summary: str) -> None:
    ensure_dir(changelog_path.parent)
    if changelog_path.exists():
        existing = changelog_path.read_text(encoding="utf-8", errors="ignore")
    else:
        existing = "# AI Docs Changelog\\n\\n"
    entry = f"## {{now_utc()}}\\n- {{summary}}\\n\\n"
    changelog_path.write_text(existing + entry, encoding="utf-8")


def write_metadata(project_dir: Path, ctx: dict, generated_files: list[str]) -> None:
    metadata_path = project_dir / ".ai-docs" / "metadata.json"
    ensure_dir(metadata_path.parent)
    payload = {{
        "generator_version": GENERATOR_VERSION,
        "generated_at": ctx["generated_at"],
        "target_os": ctx["target_os"],
        "project_type": ctx["project_type"],
        "agents": ctx["agents"],
        "stack": ctx["stack"],
        "master_prompt_sha256": hash_text(MASTER_PROMPT),
        "generated_files": generated_files,
    }}
    metadata_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def compute_stale_reasons(project_dir: Path, ctx: dict) -> list[str]:
    reasons = []
    metadata_path = project_dir / ".ai-docs" / "metadata.json"
    if not metadata_path.exists():
        reasons.append("No prior metadata found; initial generation is required.")
        return reasons

    try:
        old_meta = json.loads(metadata_path.read_text(encoding="utf-8", errors="ignore"))
    except Exception:
        reasons.append("Existing metadata could not be parsed.")
        return reasons

    old_stack = old_meta.get("stack", {{}})
    new_stack = ctx.get("stack", {{}})

    for key in ["languages", "frameworks", "package_managers"]:
        old_values = sorted(old_stack.get(key, []) or [])
        new_values = sorted(new_stack.get(key, []) or [])
        if old_values != new_values:
            reasons.append(f"Stack changed for {{key}}: {{old_values}} -> {{new_values}}")

    old_agents = sorted(old_meta.get("agents", []) or [])
    new_agents = sorted(ctx.get("agents", []) or [])
    if old_agents != new_agents:
        reasons.append(f"Enabled agents changed: {{old_agents}} -> {{new_agents}}")

    if not reasons:
        reasons.append("Generated content drift detected from templates or user-managed sections.")

    return reasons


def write_check_report(report_path: Path, changed_files: list[str], reasons: list[str], project_dir: Path) -> None:
    ensure_dir(report_path.parent)
    lines = [
        "# AI Docs Freshness Report",
        "",
        f"Generated at: {{now_utc()}}",
        f"Project: {{project_dir}}",
        "",
        "## Changed Files",
    ]
    if changed_files:
        lines.extend([f"- {{name}}" for name in changed_files])
    else:
        lines.append("- None")

    lines.extend(["", "## Likely Reasons"])
    if reasons:
        lines.extend([f"- {{reason}}" for reason in reasons])
    else:
        lines.append("- No reasons detected")

    report_path.write_text("\\n".join(lines).rstrip() + "\\n", encoding="utf-8")


def generate_files(project_dir: Path, ctx: dict, markdown_context: list[dict], check_mode: bool = False) -> tuple[list[str], list[str]]:
    generated = []
    changed_files = []

    common_files = {{
        "AGENTS.md": generate_agents_md(ctx),
        ".ai-docs/CONTEXT-SNAPSHOT.md": generate_context_snapshot(ctx, markdown_context),
        ".ai-docs/FEEDBACK.md": """# Feedback Loop

Use this file to propose improvements to generated AI docs.

## Template
- Date:
- Area:
- Problem:
- Suggested change:
- Expected outcome:
""",
        ".ai-docs/ROADMAP.md": """# AI Docs Roadmap

## Near-Term
- Keep agent docs aligned with project stack and standards.
- Add project-specific examples for common workflows.

## Mid-Term
- Automate doc freshness checks in CI.
- Add onboarding shortcuts for new contributors.
""",
        ".ai-docs/SECURITY.md": """# AI Docs Security Notes

- Never include secrets, keys, or credentials in generated docs.
- Require human review for changes touching auth, permissions, or compliance.
- Run dependency and vulnerability scans in CI.
""",
        ".ai-docs/SPEC-DRIVEN-DEVELOPMENT.md": """# Spec-Driven Development

## Pattern
1. Define requirement and acceptance criteria.
2. Write tests from criteria.
3. Implement minimal code to satisfy tests.
4. Update docs and traceability notes.
""",
        ".ai-docs/MASTER_PROMPT_REFERENCE.md": MASTER_PROMPT,
    }}

    agent_files = generate_agent_specific_docs(ctx)
    all_files = dict(common_files)
    all_files.update(agent_files)

    all_paths = sorted(all_files.keys())
    index_content = generate_index_md(ctx, all_paths)
    all_files["AI_DOCS_INDEX.md"] = index_content

    impacted_files, stack_changed, agents_changed, prompt_changed = determine_impacted_files(
        project_dir,
        ctx,
        all_files,
        agent_files,
        check_mode,
    )

    for rel_path, content in all_files.items():
        if not check_mode and rel_path not in impacted_files:
            generated.append(rel_path)
            continue
        file_path = project_dir / rel_path
        existing_content = read_text_if_exists(file_path)
        final_content = preserve_user_custom_blocks(existing_content, content)
        if normalize_text(existing_content) != normalize_text(final_content):
            changed_files.append(rel_path)
            if not check_mode:
                write_text(file_path, final_content)
        generated.append(rel_path)

    previous = load_previous_metadata(project_dir)
    stale_candidates = sorted(
        set(previous.get("generated_files", [])) - set(all_files.keys()) - {{".ai-docs/CHANGELOG.md", ".ai-docs/metadata.json"}}
    )
    for rel_path in stale_candidates:
        if not is_managed_generated_file(rel_path):
            continue
        file_path = project_dir / rel_path
        if not file_path.exists():
            continue
        if check_mode:
            changed_files.append(rel_path)
            continue
        if agents_changed or stack_changed:
            file_path.unlink()
            changed_files.append(rel_path)

    if not check_mode and changed_files:
        append_changelog(project_dir / ".ai-docs" / "CHANGELOG.md", f"Generated/updated {{len(changed_files)}} files.")
        generated.append(".ai-docs/CHANGELOG.md")

        write_metadata(project_dir, ctx, sorted(generated))
        generated.append(".ai-docs/metadata.json")

    return sorted(generated), sorted(changed_files)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate AI agent markdown docs for a project.")
    parser.add_argument("--project", default=".", help="Target project directory (default: current directory)")
    parser.add_argument(
        "--mode",
        choices=["auto", "new", "existing"],
        default="auto",
        help="Project mode detection override",
    )
    parser.add_argument("--check", action="store_true", help="Check mode: do not write files, exit non-zero if docs are out of date.")
    parser.add_argument("--non-interactive", action="store_true", help="Use defaults for prompts in new-project mode.")
    parser.add_argument("--report-path", help="Optional path to write markdown report in --check mode.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    project_dir = Path(args.project).resolve()
    if not project_dir.exists() or not project_dir.is_dir():
        raise SystemExit(f"Project path does not exist or is not a directory: {{project_dir}}")

    detected = detect_project_type(project_dir)
    mode = args.mode if args.mode != "auto" else detected

    if args.mode == "auto":
        print(f"Detected project mode: {{detected}}")
    else:
        print(f"Using override mode: {{mode}}")

    stack = detect_stack(project_dir)
    markdown_context = gather_existing_markdown_context(project_dir)

    new_details = None
    if mode == "new":
        if args.non_interactive:
            new_details = {{
                "target_os": GENERATOR_TARGET_OS if GENERATOR_TARGET_OS != "auto" else "auto",
                "agents": list(DEFAULT_AGENTS),
                "languages": [],
                "frameworks": [],
                "tests": [],
                "linting": [],
                "suggestions": [],
            }}
        elif args.check:
            print("Check mode cannot prompt for new-project questions. Use --mode existing or add --non-interactive.")
            raise SystemExit(2)
        else:
            new_details = ask_new_project_details()
        if new_details.get("languages"):
            stack["languages"] = sorted(set(stack.get("languages", []) + new_details["languages"]))
        if new_details.get("frameworks"):
            stack["frameworks"] = sorted(set(stack.get("frameworks", []) + new_details["frameworks"]))

    generated_at = resolve_generated_at(project_dir, args.check)
    ctx = build_common_context(mode, stack, new_details, generated_at)
    generated_files, changed_files = generate_files(project_dir, ctx, markdown_context, check_mode=args.check)

    if args.check:
        if changed_files:
            print("\\nAI docs are out of date. Regenerate with the bootstrap script.")
            for file_name in changed_files:
                print(f"- {{file_name}}")
            reasons = compute_stale_reasons(project_dir, ctx)
            if reasons:
                print("\\nLikely reasons:")
                for reason in reasons:
                    print(f"- {{reason}}")
            if args.report_path:
                write_check_report((project_dir / args.report_path).resolve(), changed_files, reasons, project_dir)
            raise SystemExit(1)
        if args.report_path:
            write_check_report((project_dir / args.report_path).resolve(), [], [], project_dir)
        print("\\nAI docs are up to date.")
        raise SystemExit(0)

    print("\\nAI docs generation complete.")
    print(f"Project: {{project_dir}}")
    print(f"Mode: {{mode}}")
    print(f"Managed files: {{len(generated_files)}}")
    print(f"Files changed: {{len(changed_files)}}")
    for file_name in changed_files:
        print(f"- {{file_name}}")

    if new_details and new_details.get("suggestions"):
        print("\\nSuggested next steps:")
        for item in new_details["suggestions"]:
            print(f"- {{item}}")


if __name__ == "__main__":
    main()
'''
    )


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    prompt_path = script_dir / "master-prompt.md"

    if not prompt_path.exists():
        raise SystemExit(f"Missing required file: {prompt_path}")

    master_prompt = prompt_path.read_text(encoding="utf-8")
    target_os = ask_target_os()

    if target_os in {"macos", "linux", "auto"}:
        output_name = "ai-docs-bootstrap"
    else:
        output_name = "ai-docs-bootstrap.py"

    output_path = script_dir / output_name
    bootstrap_content = build_bootstrap_script(master_prompt, target_os)
    output_path.write_text(bootstrap_content, encoding="utf-8")

    # Mark executable on Unix-like systems.
    if output_name == "ai-docs-bootstrap":
        mode = output_path.stat().st_mode
        output_path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print("\nBootstrap executable generated successfully.")
    print(f"- Source prompt: {prompt_path}")
    print(f"- Target OS profile: {target_os}")
    print(f"- Output: {output_path}")
    print("\nUsage examples:")
    if output_name == "ai-docs-bootstrap":
        print("  ./ai-docs-bootstrap --project /path/to/project")
    else:
        print("  python ai-docs-bootstrap.py --project C:\\path\\to\\project")


if __name__ == "__main__":
    main()
