"""Constants for ai-docs-bootstrap project setup."""

from .compliance import COMPLIANCE_ALIASES, COMPLIANCE_PACKS
from .hints import FRAMEWORK_INTENT_HINTS, PACKAGE_GUIDANCE, SECURITY_AUDIT_COMMANDS
from .presets import APP_ARCHETYPES, INTENT_KEYWORD_BLUEPRINTS, STACK_PRESETS

__all__ = [
    "COMPLIANCE_PACKS",
    "COMPLIANCE_ALIASES",
    "FRAMEWORK_INTENT_HINTS",
    "PACKAGE_GUIDANCE",
    "SECURITY_AUDIT_COMMANDS",
    "STACK_PRESETS",
    "APP_ARCHETYPES",
    "INTENT_KEYWORD_BLUEPRINTS",
]
