"""Prelude runtime template section for ai-docs-bootstrap."""

from __future__ import annotations


def render_runtime_prelude(
    prompt_literal: str,
    target_os_literal: str,
    stack_presets_literal: str,
    app_archetypes_literal: str,
    intent_keyword_blueprints_literal: str,
    gen_functions_setup: str,
) -> str:
    return f'''\
#!/usr/bin/env python3
"""
Drop-in executable generated by setup-ai-docs.py.
Run this file inside any project repository to generate AI agent markdown docs.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

try:
    import tomllib  # Python 3.11+
except Exception:  # pragma: no cover
    tomllib = None

MASTER_PROMPT = {prompt_literal}
GENERATOR_TARGET_OS = {target_os_literal}
GENERATOR_VERSION = "1.0.0"

DEFAULT_AGENTS = [
    "cursor",
    "github-copilot",
    "claude-code",
    "openai-codex",
    "antigravity",
]

MAX_CUSTOM_CONFIG_BYTES = 262144
MAX_CUSTOM_ITEMS = 50
MAX_CUSTOM_TEXT_LENGTH = 4000
MAX_FEATURE_CONFIG_BYTES = 65536

FEATURE_CATALOG = {{
    "base-docs": "Core shared AI docs under .ai-docs and top-level indexes",
    "agent-docs": "Agent-specific guidance files (Copilot, Claude, Codex, etc.)",
    "feature-specs": "Spec/memory scaffolding under .specs/features",
    "containerization-docs": "Containerization baseline and deployment guidance",
    "custom-agent-config": "Custom framework/compliance/template summary docs",
    "compliance-level-2": "Level 2 compliance scanning files",
    "compliance-level-3": "Level 3 compliance implementation pattern files",
    "ai-analysis": "AI-assisted compliance analysis report",
    "patch-proposals": "Level 3 patch proposal and injection reports",
    "auto-patch-apply": "Apply deterministic auto-patches and emit result report",
    "compliance-dashboard": "Compliance dashboard HTML output",
    "feature-catalog": "Generated feature status file (available and active options)",
}}

FEATURE_DEPENDENCIES = {{
    "ai-analysis": ["compliance-level-3"],
    "patch-proposals": ["compliance-level-3"],
    "auto-patch-apply": ["compliance-level-3"],
    "compliance-dashboard": ["compliance-level-3"],
}}

FEATURE_LIFECYCLE = {{
    "base-docs": {{"status": "stable"}},
    "agent-docs": {{"status": "stable"}},
    "feature-specs": {{"status": "stable"}},
    "containerization-docs": {{"status": "stable"}},
    "custom-agent-config": {{"status": "stable"}},
    "compliance-level-2": {{"status": "stable"}},
    "compliance-level-3": {{"status": "stable"}},
    "ai-analysis": {{
        "status": "experimental",
        "note": "Output may change between generator releases.",
    }},
    "patch-proposals": {{"status": "stable"}},
    "auto-patch-apply": {{
        "status": "experimental",
        "note": "Requires explicit opt-in and may change as patch safety rules evolve.",
    }},
    "compliance-dashboard": {{"status": "stable"}},
    "feature-catalog": {{"status": "stable"}},
}}

FEATURE_RENAMES = {{
    "ai-compliance-analysis": "ai-analysis",
    "dashboard-html": "compliance-dashboard",
}}

FEATURE_REMOVED = {{
    "compliance-report": "Removed in Phase 8. Use compliance-level-2 and/or compliance-level-3 outputs instead.",
}}

FEATURE_PROFILES = {{
    "minimal": [
        "base-docs",
        "agent-docs",
        "feature-specs",
        "containerization-docs",
        "feature-catalog",
    ],
    "standard": [
        "base-docs",
        "agent-docs",
        "feature-specs",
        "containerization-docs",
        "custom-agent-config",
        "compliance-level-2",
        "feature-catalog",
    ],
    "compliance-heavy": [
        "base-docs",
        "agent-docs",
        "feature-specs",
        "containerization-docs",
        "custom-agent-config",
        "compliance-level-2",
        "compliance-level-3",
        "ai-analysis",
        "patch-proposals",
        "compliance-dashboard",
        "feature-catalog",
    ],
}}


def default_active_features() -> list[str]:
    return [
        "base-docs",
        "agent-docs",
        "feature-specs",
        "containerization-docs",
        "custom-agent-config",
        "compliance-level-2",
        "compliance-level-3",
        "ai-analysis",
        "patch-proposals",
        "compliance-dashboard",
        "feature-catalog",
    ]


def default_feature_profile_name() -> str:
    return "compliance-heavy"


def normalize_feature_keys(items: list[str]) -> list[str]:
    out = []
    for item in items or []:
        key = FEATURE_RENAMES.get(slugify_intent_key(item), slugify_intent_key(item))
        if key in FEATURE_CATALOG and key not in out:
            out.append(key)
    return out


def get_feature_lifecycle(feature_name: str) -> dict:
    entry = FEATURE_LIFECYCLE.get(feature_name, {{}})
    status = str(entry.get("status") or "stable").strip().lower()
    if status not in {{"stable", "experimental", "deprecated"}}:
        status = "stable"
    note = str(entry.get("note") or "").strip()
    replacement = str(entry.get("replacement") or "").strip()
    return {{"status": status, "note": note, "replacement": replacement}}


def validate_feature_guardrails(
    active_features: list[str],
    apply_auto_patches: bool,
) -> None:
    active_set = set(active_features)
    issues = []

    for feature_name, required_features in FEATURE_DEPENDENCIES.items():
        if feature_name not in active_set:
            continue
        missing = [name for name in required_features if name not in active_set]
        if missing:
            missing_text = ", ".join(missing)
            issues.append(
                f"Feature '{{feature_name}}' requires: {{missing_text}}. "
                f"Add it with --features/--enable-features or disable '{{feature_name}}'."
            )

    if "auto-patch-apply" in active_set and not apply_auto_patches:
        issues.append(
            "Feature 'auto-patch-apply' also requires the --apply-auto-patches flag. "
            "Add the flag or remove the feature selection."
        )

    if issues:
        raise ValueError("Invalid feature combination(s):\\n- " + "\\n- ".join(issues))


def resolve_feature_profile(profile_name: str | None) -> tuple[str | None, list[str]]:
    if not profile_name:
        return None, []

    normalized = slugify_intent_key(profile_name)
    if normalized not in FEATURE_PROFILES:
        valid = ", ".join(sorted(FEATURE_PROFILES.keys()))
        raise ValueError(
            f"Unsupported feature profile: {{profile_name}}. Use --list-feature-profiles. Valid profiles: {{valid}}"
        )

    return normalized, normalize_feature_keys(FEATURE_PROFILES[normalized])


def resolve_active_features(
    feature_profile: str | None,
    explicit_features: list[str],
    enable_features: list[str],
    disable_features: list[str],
    apply_auto_patches: bool,
) -> list[str]:
    if feature_profile and explicit_features:
        raise ValueError(
            "--feature-profile cannot be combined with --features. Use the profile with --enable-features/--disable-features overrides instead."
        )

    known = set(FEATURE_CATALOG.keys())
    provided = set(explicit_features or []) | set(enable_features or []) | set(
        disable_features or []
    )
    unknown = []
    removed_issues = []
    for raw in sorted(provided):
        norm = slugify_intent_key(raw)
        if norm in FEATURE_REMOVED:
            removed_issues.append(
                f"Feature '{{raw}}' has been removed. {{FEATURE_REMOVED[norm]}}"
            )
            continue
        resolved = FEATURE_RENAMES.get(norm, norm)
        if resolved not in known:
            unknown.append(raw)
    if removed_issues:
        raise ValueError("Unsupported feature option(s):\\n- " + "\\n- ".join(removed_issues))
    if unknown:
        valid = ", ".join(sorted(FEATURE_CATALOG.keys()))
        unknown_text = ", ".join(unknown)
        raise ValueError(
            f"Unsupported feature option(s): {{unknown_text}}. Use --list-features. Valid options: {{valid}}"
        )

    if explicit_features:
        active = normalize_feature_keys(explicit_features)
    elif feature_profile:
        _, active = resolve_feature_profile(feature_profile)
    else:
        active = normalize_feature_keys(default_active_features())

    for key in normalize_feature_keys(enable_features):
        if key not in active:
            active.append(key)

    disable_set = set(normalize_feature_keys(disable_features))
    active = [key for key in active if key not in disable_set]

    if apply_auto_patches and "auto-patch-apply" not in active:
        active.append("auto-patch-apply")

    validate_feature_guardrails(active, apply_auto_patches)

    return active


def generate_feature_status_md(active_features: list[str], selected_profile: str | None = None) -> str:
    available_lines = []
    for name, desc in FEATURE_CATALOG.items():
        lifecycle = get_feature_lifecycle(name)
        note_suffix = f"; {{lifecycle['note']}}" if lifecycle["note"] else ""
        available_lines.append(
            f"- {{name}} [{{lifecycle['status']}}]: {{desc}}{{note_suffix}}"
        )
    active_lines = [f"- {{name}} [{{get_feature_lifecycle(name)['status']}}]" for name in active_features] or ["- (none)"]
    inactive_lines = [
        f"- {{name}} [{{get_feature_lifecycle(name)['status']}}]"
        for name in FEATURE_CATALOG.keys()
        if name not in set(active_features)
    ] or ["- (none)"]
    profile_text = selected_profile or "custom"

    return """# Feature Options

## Selected Profile
{{profile}}

## Available Features
{{available}}

## Active Features For This Run
{{active}}

## Inactive Features
{{inactive}}
""".format(
    profile=profile_text,
    available="\\n".join(available_lines),
    active="\\n".join(active_lines),
    inactive="\\n".join(inactive_lines),
    )


def generate_containerization_md(ctx: dict) -> str:
        stack = ctx.get("stack", {{}})
        languages = ", ".join(stack.get("languages") or ["TBD"])
        frameworks = ", ".join(stack.get("frameworks") or ["TBD"])
        package_managers = ", ".join(stack.get("package_managers") or ["TBD"])

        return f"""# Containerization Baseline

Last updated: {{ctx.get("generated_at", "unknown")}}

## Detected Stack Context
- Languages: {{languages}}
- Frameworks: {{frameworks}}
- Package managers: {{package_managers}}

## Strategy (Industry Standard)
Use a multi-stage Docker build and run containers as non-root with a minimal runtime image.

## Dockerfile Baseline
```dockerfile
# syntax=docker/dockerfile:1.7
FROM python:3.11-slim AS builder
WORKDIR /app
COPY requirements*.txt ./
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

FROM python:3.11-slim AS runtime
ENV PYTHONDONTWRITEBYTECODE=1 \\
        PYTHONUNBUFFERED=1
WORKDIR /app
RUN addgroup --system app && adduser --system --ingroup app app
COPY --from=builder /install /usr/local
COPY . .
USER app
EXPOSE 8000
CMD ["python", "-m", "app"]
```

## Docker Compose Baseline
```yaml
services:
    app:
        build:
            context: .
            target: runtime
        ports:
            - "8000:8000"
        env_file:
            - .env
        read_only: true
        security_opt:
            - no-new-privileges:true
        restart: unless-stopped
```

## Kubernetes Baseline
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: app
    template:
        metadata:
            labels:
                app: app
        spec:
            containers:
                - name: app
                    image: ghcr.io/your-org/your-app:latest
                    ports:
                        - containerPort: 8000
                    securityContext:
                        allowPrivilegeEscalation: false
                        runAsNonRoot: true
                        readOnlyRootFilesystem: true
                    resources:
                        requests:
                            cpu: "100m"
                            memory: "128Mi"
                        limits:
                            cpu: "500m"
                            memory: "512Mi"
```

## CI/CD Checklist
1. Build image on each pull request and default-branch push.
2. Scan image for vulnerabilities before release.
3. Push immutable image tags (commit SHA + semver).
4. Promote via environment-specific manifests/values, not mutable tags.
5. Run smoke tests against containerized runtime before production deploy.

## Security Checklist
- Do not bake secrets into images.
- Use a non-root user and minimal base image.
- Enable image scanning and patch base images regularly.
- Keep runtime filesystem read-only where possible.
- Pin dependencies and verify provenance in CI.
"""

STACK_PRESETS = {stack_presets_literal}

APP_ARCHETYPES = {app_archetypes_literal}

INTENT_KEYWORD_BLUEPRINTS = {intent_keyword_blueprints_literal}

COMPLIANCE_PACKS = {{
    "pci-dss": {{
        "name": "PCI DSS",
        "trigger_keywords": ["wallet", "ewallet", "payments", "fintech", "checkout", "commerce"],
        "checks": [
            "Tokenize payment data and avoid storing PAN/CVV in application systems.",
            "Enforce network segmentation and least-privilege access for payment paths.",
            "Run regular vulnerability scans and monitored audit trails for card workflows.",
        ],
    }},
    "hipaa": {{
        "name": "HIPAA",
        "trigger_keywords": ["health", "clinic", "ehr", "emr", "telemedicine", "patient"],
        "checks": [
            "Restrict PHI access with role-based controls and just-in-time authorization.",
            "Encrypt PHI in transit and at rest with key rotation and access logs.",
            "Maintain breach response procedures and immutable access audit trails.",
        ],
    }},
    "soc2": {{
        "name": "SOC 2",
        "trigger_keywords": ["saas", "b2b", "enterprise", "tenant"],
        "checks": [
            "Document change management and approval workflows for production releases.",
            "Enforce periodic access reviews, offboarding, and least-privilege controls.",
            "Track availability/security incidents and corrective actions with evidence.",
        ],
    }},
    "gdpr": {{
        "name": "GDPR",
        "trigger_keywords": ["social", "analytics", "adtech", "tracking", "marketing", "profile"],
        "checks": [
            "Implement consent management and lawful-basis tracking for personal data.",
            "Support data subject rights: export, correction, deletion, and processing restrictions.",
            "Apply data minimization and retention policies with enforcement automation.",
        ],
    }},
    "ccpa": {{
        "name": "CCPA/CPRA",
        "trigger_keywords": ["social", "analytics", "adtech", "consumer", "tracking"],
        "checks": [
            "Implement do-not-sell/share controls and consumer data access requests.",
            "Classify personal information categories and purpose of use.",
            "Audit third-party data sharing and contractual obligations.",
        ],
    }},
    "iso27001": {{
        "name": "ISO 27001",
        "trigger_keywords": ["enterprise", "gov", "government", "public-sector", "b2b", "saas"],
        "checks": [
            "Maintain risk register, treatment plans, and control ownership evidence.",
            "Define asset inventory and classification with handling requirements.",
            "Run incident response exercises and control effectiveness reviews.",
        ],
    }},
}}

COMPLIANCE_ALIASES = {{
    "pci": "pci-dss",
    "pcidss": "pci-dss",
    "pci-dss": "pci-dss",
    "hipaa": "hipaa",
    "soc2": "soc2",
    "soc-2": "soc2",
    "gdpr": "gdpr",
    "ccpa": "ccpa",
    "cpra": "ccpa",
    "iso27001": "iso27001",
    "iso-27001": "iso27001",
}}

FRAMEWORK_INTENT_HINTS = {{
    "Next.js": {{"E-Commerce": 2, "AdTech": 1}},
    "React": {{"Social App": 1, "E-Commerce": 1}},
    "Express": {{"Ride Booking": 1, "E-Commerce": 1, "AdTech": 1}},
    "Fastify": {{"Ride Booking": 1, "AdTech": 1}},
    "NestJS": {{"B2B SaaS": 1, "IoT Platform": 1}},
    "Laravel": {{"E-Commerce": 2, "CRM": 1}},
    "FastAPI": {{"Analytics": 1, "Health Tech": 1, "Scraper / Data Ingestion": 1}},
    "Django": {{"CRM": 1, "EdTech": 1, "Health Tech": 1}},
    "Spring Boot": {{"B2B SaaS": 1, "GovTech": 1}},
    "ASP.NET Core": {{"B2B SaaS": 1, "GovTech": 1}},
}}

PACKAGE_GUIDANCE = {{
    "React": {{
        "recommended": ["react-query (@tanstack/react-query)", "zod", "react-hook-form", "date-fns"],
        "avoid": ["moment -> prefer date-fns/dayjs", "redux-form -> prefer react-hook-form"],
    }},
    "Next.js": {{
        "recommended": ["next-safe-action", "zod", "@tanstack/react-query", "next-auth/auth.js"],
        "avoid": ["next-routes -> use App Router", "moment -> prefer date-fns/dayjs"],
    }},
    "Express": {{
        "recommended": ["zod", "pino", "helmet", "rate-limiter-flexible"],
        "avoid": ["request -> use native fetch/undici", "winston-only stacks -> consider pino for perf"],
    }},
    "Fastify": {{
        "recommended": ["@fastify/helmet", "@fastify/rate-limit", "zod", "pino"],
        "avoid": ["request -> use native fetch/undici"],
    }},
    "NestJS": {{
        "recommended": ["class-validator", "class-transformer", "@nestjs/swagger", "pino"],
        "avoid": ["request -> use native fetch/undici"],
    }},
    "Vue": {{
        "recommended": ["pinia", "vue-query", "zod", "dayjs"],
        "avoid": ["moment -> prefer dayjs/date-fns"],
    }},
    "Angular": {{
        "recommended": ["ngrx", "zod", "rxjs", "date-fns"],
        "avoid": ["tslint -> use eslint"],
    }},
    "Laravel": {{
        "recommended": ["laravel/sanctum", "spatie/laravel-permission", "laravel/pint", "larastan/larastan"],
        "avoid": ["abandoned packages in composer.lock -> replace with maintained alternatives"],
    }},
    "FastAPI": {{
        "recommended": ["pydantic-settings", "httpx", "sqlmodel/alembic", "structlog"],
        "avoid": ["requests in async routes -> use httpx", "pydantic v1-only libs -> prefer v2-ready libs"],
    }},
    "Django": {{
        "recommended": ["django-environ", "django-filter", "djangorestframework", "sentry-sdk"],
        "avoid": ["django-rest-swagger -> use drf-spectacular"],
    }},
}}

SECURITY_AUDIT_COMMANDS = {{
    "npm/pnpm/yarn": [
        "npm audit --omit=dev",
        "pnpm audit",
        "yarn npm audit",
    ],
    "pip/poetry": [
        "python -m pip install pip-audit",
        "pip-audit",
        "poetry export -f requirements.txt --without-hashes | pip-audit -r /dev/stdin",
    ],
    "composer": [
        "composer audit",
    ],
    "go modules": [
        "go install golang.org/x/vuln/cmd/govulncheck@latest",
        "govulncheck ./...",
    ],
    "cargo": [
        "cargo install cargo-audit",
        "cargo audit",
    ],
    "nuget": [
        "dotnet list package --vulnerable --include-transitive",
    ],
    "maven/gradle": [
        "mvn org.owasp:dependency-check-maven:check",
        "./gradlew dependencyCheckAnalyze",
    ],
    "bundler": [
        "bundle audit check --update",
    ],
    "SwiftPM": [
        "swift package resolve && swift package show-dependencies",
    ],
}}


if TYPE_CHECKING:
    # Stubs for functions injected via exec() later in this generated script.
    # This keeps Ruff/Pylance from reporting undefined symbols in call sites.
    def sanitize_feature_name(name: str) -> str: ...

    def detect_feature_names(project_dir: Path, max_features: int = 8) -> list[str]: ...

    def write_metadata_simple(
        project_dir: Path, ctx: dict, generated_files: list[str]
    ) -> None: ...

    def build_feature_spec_files(
        feature_names: list[str], locale: str = "en"
    ) -> tuple[dict[str, str], str]: ...

    def generate_agents_md(ctx: dict) -> str: ...

    def generate_app_blueprint_md(ctx: dict) -> str: ...

    def generate_index_md(ctx: dict, files: list[str]) -> str: ...

    def generate_context_snapshot(ctx: dict, markdown_context: list[dict]) -> str: ...

    def generate_agent_specific_docs(ctx: dict) -> dict[str, str]: ...

    def generate_level_2_compliance_scanning(
        compliance_packs: list[dict], locale: str = "en", compliance_region: str = ""
    ) -> dict[str, str]: ...

    def generate_level_3_compliance_patterns(
        compliance_packs: list[dict], locale: str = "en", compliance_region: str = ""
    ) -> dict[str, str]: ...

    def generate_level_3_pattern_injection_report(
        project_dir: Path, compliance_packs: list[dict]
    ) -> str | None: ...

    def generate_level_3_patch_proposals(
        project_dir: Path, compliance_packs: list[dict], max_proposals_per_rule: int = 3
    ) -> str | None: ...

    def generate_ai_assisted_compliance_analysis(
        project_dir: Path, compliance_packs: list[dict], max_findings: int = 12
    ) -> str | None: ...

    def generate_compliance_dashboard_html(
        project_dir: Path,
        compliance_packs: list[dict],
        planned_output_paths: list[str] | None = None,
    ) -> str: ...

    def apply_level_3_patch_proposals(
        project_dir: Path,
        compliance_packs: list[dict],
        max_patches_per_rule: int = 3,
        patch_allowlist: list[str] | None = None,
        patch_denylist: list[str] | None = None,
    ) -> dict[str, list[dict]]: ...

    def generate_level_3_applied_patch_report(
        project_dir: Path, applied_items: list[dict]
    ) -> str | None: ...

    def read_text_if_exists(path: Path) -> str: ...

    def normalize_text(content: str) -> str: ...

    def write_text(path: Path, content: str) -> None: ...

    def append_changelog(changelog_path: Path, summary: str, now_utc_fn: Any = None) -> None: ...

    def load_previous_metadata(project_dir: Path) -> dict: ...

    def compute_stale_reasons(project_dir: Path, ctx: dict) -> list[str]: ...

    def write_check_report(
        path: Path,
        changed_files: list[str],
        reasons: list[str],
        project_dir: Path,
    ) -> None: ...


def now_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def hash_text(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def current_script_sha256() -> str:
    try:
        content = Path(__file__).read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return ""
    return hash_text(content)


def merge_unique(existing: list[str], incoming: list[str]) -> list[str]:
    merged = []
    seen = set()
    for item in (existing or []) + (incoming or []):
        value = item.strip()
        if not value:
            continue
        key = value.lower()
        if key in seen:
            continue
        seen.add(key)
        merged.append(value)
    return merged


def slugify_intent_key(value: str) -> str:
    key = re.sub(r"[^a-z0-9]+", "-", (value or "").strip().lower()).strip("-")
    return key or "general-app"


def parse_compliance_input(raw: str) -> list[str]:
    if not raw.strip():
        return []

    items = []
    for part in raw.split(","):
        key = slugify_intent_key(part)
        mapped = COMPLIANCE_ALIASES.get(key)
        if mapped:
            items.append(mapped)
    return merge_unique([], items)


def parse_csv_items(raw: str) -> list[str]:
    if not raw:
        return []
    cleaned = []
    for item in raw.split(","):
        value = item.strip()
        if not value:
            continue
        if len(value) > 120:
            value = value[:120]
        cleaned.append(value)
        if len(cleaned) >= MAX_CUSTOM_ITEMS:
            break
    return cleaned


def _normalize_feature_config_items(raw_value: object, field_name: str) -> list[str]:
    if raw_value is None:
        return []
    if not isinstance(raw_value, list):
        raise ValueError(f"Field '{{field_name}}' in --features-config must be an array of strings.")

    values = []
    for item in raw_value:
        if not isinstance(item, str):
            raise ValueError(f"Field '{{field_name}}' in --features-config must contain only strings.")
        value = item.strip()
        if not value:
            continue
        if len(value) > 120:
            value = value[:120]
        values.append(value)
        if len(values) >= MAX_CUSTOM_ITEMS:
            break
    return values


def _sanitize_feature_config_payload(payload: dict) -> dict:
    allowed_keys = {{
        "feature_profile",
        "features",
        "enable_features",
        "disable_features",
        "apply_auto_patches",
    }}
    unknown = sorted(set(payload.keys()) - allowed_keys)
    if unknown:
        allowed_text = ", ".join(sorted(allowed_keys))
        unknown_text = ", ".join(unknown)
        raise ValueError(
            f"Unknown key(s) in --features-config: {{unknown_text}}. Allowed keys: {{allowed_text}}"
        )

    out = {{}}
    feature_profile = payload.get("feature_profile")
    if feature_profile is not None:
        if not isinstance(feature_profile, str):
            raise ValueError("Field 'feature_profile' in --features-config must be a string.")
        cleaned_profile = feature_profile.strip()
        if cleaned_profile:
            out["feature_profile"] = cleaned_profile[:120]

    out["features"] = _normalize_feature_config_items(payload.get("features"), "features")
    out["enable_features"] = _normalize_feature_config_items(payload.get("enable_features"), "enable_features")
    out["disable_features"] = _normalize_feature_config_items(payload.get("disable_features"), "disable_features")

    auto_patch_value = payload.get("apply_auto_patches")
    if auto_patch_value is not None and not isinstance(auto_patch_value, bool):
        raise ValueError("Field 'apply_auto_patches' in --features-config must be a boolean.")
    out["apply_auto_patches"] = bool(auto_patch_value)

    return out


def load_feature_config(path_value: str | None) -> dict:
    if not path_value:
        return {{}}

    config_path = Path(path_value).expanduser()
    if not config_path.exists() or not config_path.is_file():
        raise ValueError(f"Feature config not found: {{config_path}}")
    if config_path.suffix.lower() != ".json":
        raise ValueError(f"Feature config must be a .json file: {{config_path}}")
    try:
        if config_path.stat().st_size > MAX_FEATURE_CONFIG_BYTES:
            raise ValueError(
                f"Feature config too large: {{config_path}}. Max bytes: {{MAX_FEATURE_CONFIG_BYTES}}"
            )
    except OSError as exc:
        raise ValueError(f"Unable to read feature config file metadata: {{config_path}}") from exc

    try:
        payload = json.loads(config_path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise ValueError(f"Invalid feature config JSON: {{config_path}}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"Feature config must be a JSON object: {{config_path}}")

    return _sanitize_feature_config_payload(payload)


def write_feature_config(
    path_value: str,
    selected_feature_profile: str | None,
    active_features: list[str],
    enable_features: list[str],
    disable_features: list[str],
    apply_auto_patches: bool,
) -> Path:
    output_path = Path(path_value).expanduser()
    payload = {{
        "schema_version": 1,
        "feature_profile": selected_feature_profile,
        "features": list(active_features),
        "enable_features": list(enable_features),
        "disable_features": list(disable_features),
        "apply_auto_patches": bool(apply_auto_patches),
    }}
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return output_path


def normalize_custom_compliance_rules(raw_rules: list[dict] | None) -> list[dict]:
    normalized = []
    for rule in raw_rules or []:
        if len(normalized) >= MAX_CUSTOM_ITEMS:
            break
        if not isinstance(rule, dict):
            continue
        raw_key = str(rule.get("key") or rule.get("name") or "").strip()
        if not raw_key:
            continue
        checks = [str(item).strip()[:200] for item in rule.get("checks", []) if str(item).strip()][:MAX_CUSTOM_ITEMS]
        normalized.append(
            {{
                "key": slugify_intent_key(raw_key),
                "name": str(rule.get("name") or raw_key).strip(),
                "checks": checks,
            }}
        )
    return normalized


def normalize_custom_feature_templates(raw_templates: list[dict] | None) -> list[dict]:
    templates = []
    for item in raw_templates or []:
        if len(templates) >= MAX_CUSTOM_ITEMS:
            break
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or "").strip()
        template = str(item.get("template") or "").strip()
        if not name or not template:
            continue
        templates.append({{"name": sanitize_feature_name(name), "template": template[:MAX_CUSTOM_TEXT_LENGTH]}})
    return templates


def _sanitize_custom_config_payload(payload: dict) -> dict:
    allowed_keys = {{
        "custom_frameworks",
        "custom_compliance_rules",
        "custom_feature_templates",
    }}
    sanitized = {{}}
    for key in allowed_keys:
        if key in payload:
            sanitized[key] = payload[key]
    return sanitized


def load_custom_config(path_value: str | None) -> dict:
    if not path_value:
        return {{}}
    config_path = Path(path_value).expanduser()
    if not config_path.exists() or not config_path.is_file():
        print(f"Custom config not found: {{config_path}}. Skipping.")
        return {{}}
    if config_path.suffix.lower() != ".json":
        print(f"Custom config must be a .json file: {{config_path}}. Skipping.")
        return {{}}
    try:
        if config_path.stat().st_size > MAX_CUSTOM_CONFIG_BYTES:
            print(f"Custom config too large: {{config_path}}. Skipping.")
            return {{}}
    except Exception:
        print(f"Unable to stat custom config: {{config_path}}. Skipping.")
        return {{}}
    try:
        payload = json.loads(config_path.read_text(encoding="utf-8"))
    except Exception:
        print(f"Invalid custom config JSON: {{config_path}}. Skipping.")
        return {{}}
    if not isinstance(payload, dict):
        print(f"Custom config must be a JSON object: {{config_path}}. Skipping.")
        return {{}}
    return _sanitize_custom_config_payload(payload)


def detect_project_type(project_dir: Path) -> str:
    manifest_candidates = [
        "package.json",
        "composer.json",
        "Package.swift",
        "pyproject.toml",
        "requirements.txt",
        "go.mod",
        "Cargo.toml",
        "pom.xml",
        "build.gradle",
        "Gemfile",
    ]
    has_manifest = any((project_dir / name).exists() for name in manifest_candidates)
    has_source = any((project_dir / d).exists() for d in ["src", "app", "services", "backend", "frontend"])
    has_docs = any(project_dir.glob("*.md"))
    has_xcodeproj = any(project_dir.glob("*.xcodeproj")) or any(project_dir.glob("*.xcworkspace"))
    return "existing" if (has_manifest or has_source or has_docs or has_xcodeproj) else "new"


def read_json_file(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {{}}


def parse_requirements_txt(path: Path) -> list[str]:
    deps = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        dep = re.split(r"[<>=~! ]", line, maxsplit=1)[0].strip()
        if dep:
            deps.append(dep)
    return deps


def parse_toml_dependencies(path: Path) -> list[str]:
    if not tomllib:
        return []
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []

    deps = []
    project = data.get("project", {{}})
    for dep in project.get("dependencies", []) or []:
        dep_name = re.split(r"[<>=~! ]", dep, maxsplit=1)[0].strip()
        if dep_name:
            deps.append(dep_name)

    poetry = data.get("tool", {{}}).get("poetry", {{}})
    poetry_deps = poetry.get("dependencies", {{}})
    for name in poetry_deps:
        if name.lower() != "python":
            deps.append(name)

    return sorted(set(deps))


def detect_stack(project_dir: Path) -> dict:
    languages = set()
    frameworks = set()
    package_managers = set()
    packages = set()
    scripts = {{}}

    package_json = project_dir / "package.json"
    if package_json.exists():
        languages.update(["JavaScript", "TypeScript"])
        package_managers.add("npm/pnpm/yarn")
        data = read_json_file(package_json)
        deps = data.get("dependencies", {{}})
        dev_deps = data.get("devDependencies", {{}})
        all_deps = {{**deps, **dev_deps}}
        packages.update(all_deps.keys())
        scripts = data.get("scripts", {{}})

        framework_map = {{
            "react": "React",
            "react-native": "React Native",
            "next": "Next.js",
            "vue": "Vue",
            "nuxt": "Nuxt",
            "svelte": "Svelte",
            "@angular/core": "Angular",
            "express": "Express",
            "@nestjs/core": "NestJS",
            "nestjs": "NestJS",
            "fastify": "Fastify",
            "hono": "Hono",
            "astro": "Astro",
            "@remix-run/react": "Remix",
        }}
        for dep_name, fw in framework_map.items():
            if dep_name in all_deps:
                frameworks.add(fw)

    composer_json = project_dir / "composer.json"
    if composer_json.exists():
        languages.add("PHP")
        package_managers.add("composer")
        data = read_json_file(composer_json)
        req = data.get("require", {{}})
        req_dev = data.get("require-dev", {{}})
        all_php = {{**req, **req_dev}}
        packages.update(all_php.keys())

        php_framework_map = {{
            "laravel/framework": "Laravel",
            "laravel/lumen-framework": "Lumen",
            "symfony/symfony": "Symfony",
        }}
        for dep_name, fw in php_framework_map.items():
            if dep_name in all_php:
                frameworks.add(fw)

    pyproject = project_dir / "pyproject.toml"
    requirements = project_dir / "requirements.txt"
    if pyproject.exists() or requirements.exists():
        languages.add("Python")
        package_managers.add("pip/poetry")
        if pyproject.exists():
            packages.update(parse_toml_dependencies(pyproject))
        if requirements.exists():
            packages.update(parse_requirements_txt(requirements))

        py_framework_map = {{
            "fastapi": "FastAPI",
            "django": "Django",
            "flask": "Flask",
            "pydantic": "Pydantic",
        }}
        pkg_lower = {{p.lower() for p in packages}}
        for dep_name, fw in py_framework_map.items():
            if dep_name in pkg_lower:
                frameworks.add(fw)

    if (project_dir / "go.mod").exists():
        languages.add("Go")
        package_managers.add("go modules")

    if (project_dir / "Cargo.toml").exists():
        languages.add("Rust")
        package_managers.add("cargo")

    if list(project_dir.glob("*.csproj")):
        languages.add("C#")
        package_managers.add("nuget")

    if (project_dir / "pom.xml").exists() or (project_dir / "build.gradle").exists():
        languages.add("Java")
        package_managers.add("maven/gradle")

    if (project_dir / "Gemfile").exists():
        languages.add("Ruby")
        package_managers.add("bundler")

    package_swift = project_dir / "Package.swift"
    if package_swift.exists():
        languages.add("Swift")
        package_managers.add("SwiftPM")
        try:
            swift_text = package_swift.read_text(encoding="utf-8", errors="ignore").lower()
        except Exception:
            swift_text = ""

        if "vapor" in swift_text:
            frameworks.add("Vapor")
        if "swiftui" in swift_text:
            frameworks.add("SwiftUI")

    has_xcodeproj = any(project_dir.glob("*.xcodeproj")) or any(project_dir.glob("*.xcworkspace"))
    if has_xcodeproj:
        languages.add("Swift")
        package_managers.add("Xcode")
        if not frameworks:
            frameworks.add("SwiftUI")

    return {{
        "languages": sorted(languages),
        "frameworks": sorted(frameworks),
        "package_managers": sorted(package_managers),
        "packages": sorted(packages),
        "scripts": scripts,
    }}


def gather_existing_markdown_context(
    project_dir: Path,
    max_files: int = 20,
    preview_chars: int = 500,
) -> list[dict]:
    generated_roots = (
        "AGENTS.md",
        "AI_DOCS_INDEX.md",
        "CLAUDE.md",
        "CODEX.md",
        "ANTIGRAVITY.md",
    )
    docs = []
    max_files = max(1, min(int(max_files), 200))
    preview_chars = max(100, min(int(preview_chars), 8000))
    for md_file in sorted(project_dir.rglob("*.md")):
        rel = md_file.relative_to(project_dir).as_posix()
        if rel.startswith(".git/"):
            continue
        if rel.startswith(".ai-docs/"):
            continue
        if rel.startswith(".github/") or rel.startswith(".cursor/"):
            continue
        if rel in generated_roots:
            continue
        try:
            content = md_file.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        docs.append({{"path": rel, "preview": content[:preview_chars].strip()}})
        if len(docs) >= max_files:
            break
    return docs


def write_session_state(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def ask_new_project_details() -> dict:
    print("\\nDetected a NEW project. Please provide setup details.")
    print("Available stack presets: " + ", ".join(sorted(STACK_PRESETS.keys())))
    print("Starter app intents: " + ", ".join(sorted(APP_ARCHETYPES.keys())))
    print(
        "You can enter any custom app intent (examples: analytics, crash-logger, social-app, ewallet, chat-app, ride-booking, ecommerce, scraper, gaming, travel, legal-tech, gov-tech, ad-tech)."
    )
    print("Intent ranking is automatic when multiple domains are present (e.g. ride-booking ecommerce).")

    os_value = input("Target OS (macos/linux/windows, default auto): ").strip().lower() or "auto"
    locale = input("Locale for generated docs (en/es/fr, default en): ").strip().lower() or "en"
    compliance_region = input("Compliance region variant (optional: us/eu/apac/latam): ").strip().lower()
    preset = input("Stack preset (optional, press Enter to skip): ").strip().lower()
    app_intent_input = (
        input(
            "App intent (any value, e.g. general-app/chatbot/crm/analytics/crash-logger/social/ewallet/chat-app/ride-booking/ecommerce/scraper/gaming/travel/legal-tech/gov-tech/ad-tech; default general-app): "
        )
        .strip()
        .lower()
        or "general-app"
    )
    agents_raw = input(
        "Agents (comma separated, default: cursor,github-copilot,claude-code,openai-codex,antigravity): "
    ).strip()
    lang_raw = input("Languages (comma separated, e.g. TypeScript,Python): ").strip()
    fw_raw = input("Frameworks (comma separated, e.g. React,FastAPI): ").strip()
    test_raw = input("Testing tools (comma separated, e.g. vitest,pytest): ").strip()
    lint_raw = input("Lint/format tools (comma separated, e.g. eslint,prettier,ruff): ").strip()
    custom_frameworks_raw = input("Custom frameworks (optional comma separated, e.g. InternalSDK,GraphQL Mesh): ").strip()
    custom_config_path = input("Custom config JSON path (optional, includes custom compliance rules/templates): ").strip()
    
    # Ask about compliance level
    print("\\n" + "="*70)
    print("COMPLIANCE LEVEL SELECTION")
    print("="*70)
    print("\\nChoose the depth of compliance documentation:")
    print("\\n  Level 1: Checklists & Requirements")
    print("    - Compliance checklists with requirement items")
    print("    - Security best practices checklist")
    print("    - Risk assessment template")
    print("    - Good for: Small teams, initial audit prep")
    print("\\n  Level 2: Scanning & Validation")
    print("    - All of Level 1, plus:")
    print("    - Code scanning rules (security patterns to detect)")
    print("    - Configuration validation scripts")
    print("    - Dependency audit commands")
    print("    - Good for: CI/CD integration, ongoing validation")
    print("\\n  Level 3: Patterns & Implementation Examples")
    print("    - All of Level 2, plus:")
    print("    - Working code examples (Python, Node.js, Go)")
    print("    - Implementation patterns for each requirement")
    print("    - Acceptance criteria & test examples")
    print("    - Good for: Enterprise teams, development guidance")
    print("\\n  Level 0: Skip (no compliance docs)")
    print("="*70)
    
    compliance_level_raw = input("Compliance level (0/1/2/3, default 1): ").strip() or "1"
    compliance_raw = input("Compliance packs (optional comma separated: pci-dss,hipaa,soc2,gdpr,ccpa,iso27001): ").strip()

    agents = [a.strip() for a in agents_raw.split(",") if a.strip()] if agents_raw else list(DEFAULT_AGENTS)
    languages = [lang.strip() for lang in lang_raw.split(",") if lang.strip()]
    frameworks = [f.strip() for f in fw_raw.split(",") if f.strip()]
    tests = [t.strip() for t in test_raw.split(",") if t.strip()]
    linting = [lint_item.strip() for lint_item in lint_raw.split(",") if lint_item.strip()]

    preset_data = STACK_PRESETS.get(preset, {{}})
    if preset and not preset_data:
        print(f"Unknown preset '{{preset}}'. Continuing without preset.")

    languages = merge_unique(preset_data.get("languages", []), languages)
    frameworks = merge_unique(preset_data.get("frameworks", []), frameworks)
    tests = merge_unique(preset_data.get("tests", []), tests)
    linting = merge_unique(preset_data.get("linting", []), linting)

    stack_hint = {{"frameworks": frameworks, "languages": languages}}
    app_intent, app_intent_display, app_data = resolve_app_blueprint(app_intent_input, stack_hint)
    selected_compliance = parse_compliance_input(compliance_raw)
    compliance_packs = resolve_compliance_packs(app_intent_display, selected_compliance)

    custom_config = load_custom_config(custom_config_path)
    custom_frameworks = parse_csv_items(custom_frameworks_raw)
    config_custom_frameworks = custom_config.get("custom_frameworks")
    if isinstance(config_custom_frameworks, list):
        config_framework_items = [str(item).strip() for item in config_custom_frameworks if str(item).strip()]
    else:
        config_framework_items = parse_csv_items(str(config_custom_frameworks or ""))
    custom_frameworks = merge_unique(custom_frameworks, config_framework_items)
    custom_compliance_rules = normalize_custom_compliance_rules(custom_config.get("custom_compliance_rules"))
    custom_feature_templates = normalize_custom_feature_templates(custom_config.get("custom_feature_templates"))

    suggestions = []
    suggestions.extend(preset_data.get("suggestions", []))
    suggestions.extend(app_data.get("suggestions", []))
    for pack in compliance_packs:
        suggestions.append(f"Compliance focus ({{pack['name']}}): {{', '.join(pack.get('checks', [])[:2])}}")
    lset = {{x.lower() for x in languages}}
    fset = {{x.lower() for x in frameworks}}

    if "typescript" in lset and "react" in fset:
        suggestions.append("Use eslint + prettier + type-aware strict tsconfig.")
        suggestions.append("Prefer vitest + testing-library for unit/integration tests.")
    if "python" in lset:
        suggestions.append("Use ruff + mypy + pytest with pre-commit hooks.")
    if "fastapi" in fset:
        suggestions.append("Add pydantic validation and contract tests for API schemas.")
    if app_intent == "chatbot":
        suggestions.append("Track conversation quality metrics (groundedness, relevance, safety).")
        if "react" in fset or "next.js" in fset:
            suggestions.append("Design a streaming chat UI with retry/fallback and transcript persistence.")
        if "express" in fset or "nestjs" in fset or "fastify" in fset:
            suggestions.append("Isolate model provider adapters behind interfaces for easy vendor switching.")
        if "laravel" in fset:
            suggestions.append("Use queued jobs for async model/retrieval calls and persist session context.")
        if "python" in lset or "fastapi" in fset or "django" in fset:
            suggestions.append("Protect model endpoints with per-tenant quotas and structured prompt telemetry.")
    if app_intent == "crm":
        suggestions.append("Define account/contact/opportunity schemas and lifecycle transitions explicitly.")
        suggestions.append("Require permission checks and audit trails on every write path.")

    suggestions = merge_unique([], suggestions)

    # Validate compliance level
    try:
        compliance_level = int(compliance_level_raw)
        if compliance_level not in (0, 1, 2, 3):
            print(f"Invalid compliance level {{compliance_level}}. Using default level 1.")
            compliance_level = 1
    except ValueError:
        print(f"Invalid compliance level '{{compliance_level_raw}}'. Using default level 1.")
        compliance_level = 1

    return {{
        "target_os": os_value,
        "locale": locale,
        "compliance_region": compliance_region,
        "preset": preset,
        "app_intent": app_intent,
        "app_intent_input": app_intent_display,
        "agents": agents,
        "languages": languages,
        "frameworks": frameworks,
        "custom_frameworks": custom_frameworks,
        "tests": tests,
        "linting": linting,
        "compliance_keys": [pack["key"] for pack in compliance_packs],
        "custom_compliance_rules": custom_compliance_rules,
        "custom_feature_templates": custom_feature_templates,
        "compliance_level": compliance_level,
        "suggestions": suggestions,
    }}


def print_catalogs(show_stack_presets: bool, show_intents: bool, show_compliance: bool) -> None:
    if show_stack_presets:
        print("\\nAvailable stack presets:")
        for key in sorted(STACK_PRESETS.keys()):
            preset = STACK_PRESETS.get(key, {{}})
            langs = ", ".join(preset.get("languages", [])) or "n/a"
            fws = ", ".join(preset.get("frameworks", [])) or "n/a"
            print(f"- {{key}} (languages: {{langs}}; frameworks: {{fws}})")

    if show_intents:
        print("\\nStarter intents:")
        for key in sorted(APP_ARCHETYPES.keys()):
            print(f"- {{key}}")

        print("\\nIntent profiles matched by keywords:")
        labels = []
        for _, blueprint in INTENT_KEYWORD_BLUEPRINTS:
            label = blueprint.get("label")
            if label:
                labels.append(label)
        for label in sorted(set(labels)):
            print(f"- {{label}}")

    if show_compliance:
        print("\\nCompliance packs:")
        for key in sorted(COMPLIANCE_PACKS.keys()):
            pack = COMPLIANCE_PACKS[key]
            name = pack.get("name", key.upper())
            print(f"- {{key}} ({{name}})")

    if not any([show_stack_presets, show_intents, show_compliance]):
        print("No catalog flag selected.")



def list_signature(values: list[str] | None) -> list[str]:
    return sorted((values or []), key=lambda item: item.lower())


def detect_scope_changes(previous: dict, ctx: dict) -> tuple[bool, bool, bool]:
    old_stack = previous.get("stack", {{}})
    new_stack = ctx.get("stack", {{}})
    stack_changed = any(
        list_signature(old_stack.get(key)) != list_signature(new_stack.get(key))
        for key in ["languages", "frameworks", "package_managers"]
    )

    agents_changed = list_signature(previous.get("agents")) != list_signature(ctx.get("agents"))
    prompt_changed = previous.get("master_prompt_sha256") != hash_text(MASTER_PROMPT)
    script_changed = previous.get("script_sha256") != current_script_sha256()
    old_intent = (previous.get("app_intent") or "").strip().lower()
    new_intent = (ctx.get("app_intent") or "").strip().lower()

    old_compliance = sorted(previous.get("compliance_keys", []) or [])
    new_compliance = sorted([pack.get("key") for pack in (ctx.get("compliance_packs", []) or []) if pack.get("key")])

    profile_changed = (old_intent != new_intent) or (old_compliance != new_compliance)
    return stack_changed, agents_changed, (prompt_changed or profile_changed or script_changed)


def determine_impacted_files(
    project_dir: Path,
    ctx: dict,
    all_files: dict[str, str],
    agent_files: dict[str, str],
    check_mode: bool,
) -> tuple[set[str], bool, bool, bool]:
    if check_mode:
        return set(all_files.keys()), True, True, True

    previous = load_previous_metadata(project_dir)
    if not previous:
        return set(all_files.keys()), True, True, True

    stack_changed, agents_changed, prompt_changed = detect_scope_changes(previous, ctx)
    impacted = {{".ai-docs/CONTEXT-SNAPSHOT.md"}}

    if stack_changed:
        impacted = set(all_files.keys())
    else:
        if agents_changed:
            impacted.update(agent_files.keys())
            impacted.update({{"AGENTS.md", "AI_DOCS_INDEX.md"}})
        if prompt_changed:
            impacted.add(".ai-docs/MASTER_PROMPT_REFERENCE.md")

    return impacted, stack_changed, agents_changed, prompt_changed


def is_managed_generated_file(path: str) -> bool:
    managed_roots = {{
        "AGENTS.md",
        "AI_DOCS_INDEX.md",
        ".cursor/rules/project.mdc",
        ".github/copilot-instructions.md",
        ".specs/README.md",
        ".specs/memory.md",
        ".specs/features/core/spec.md",
        ".specs/features/core/memory.md",
        ".ai-docs/MEMORY-MANAGEMENT.md",
        ".ai-docs/CODE-GENERATION-STANDARDS.md",
    }}
    if path in managed_roots:
        return True
    if path.startswith(".ai-docs/"):
        return True
    if path.startswith(".specs/features/"):
        return True
    return False


CUSTOM_BLOCK_RE = re.compile(
    r"<!--\\s*user-custom:start(?::(?P<id>[A-Za-z0-9_.-]+))?\\s*-->.*?<!--\\s*user-custom:end(?:[:][A-Za-z0-9_.-]+)?\\s*-->",
    re.DOTALL,
)


def extract_custom_blocks(content: str) -> dict[str, str]:
    blocks = {{}}
    index = 0
    for match in CUSTOM_BLOCK_RE.finditer(content or ""):
        index += 1
        block = match.group(0)
        block_id = match.group("id") or f"block_{{index}}"
        blocks[block_id] = block
    return blocks


def ensure_default_custom_block(content: str) -> str:
    if "<!-- user-custom:start" in content:
        return content
    return (
        content.rstrip()
        + "\\n\\n<!-- user-custom:start:local -->\\n"
        + "# Add project-specific guidance here.\\n"
        + "<!-- user-custom:end:local -->\\n"
    )


def preserve_user_custom_blocks(existing_content: str, new_content: str) -> str:
    merged = ensure_default_custom_block(new_content)
    existing_blocks = extract_custom_blocks(existing_content)
    new_blocks = extract_custom_blocks(merged)

    preserved_unmatched = []
    for block_id, existing_block in existing_blocks.items():
        if block_id in new_blocks:
            merged = merged.replace(new_blocks[block_id], existing_block, 1)
        else:
            preserved_unmatched.append(existing_block)

    if preserved_unmatched:
        merged = merged.rstrip() + "\\n\\n## Preserved User Customizations\\n\\n" + "\\n\\n".join(preserved_unmatched) + "\\n"

    return merged


def resolve_generated_at(project_dir: Path, check_mode: bool) -> str:
    if not check_mode:
        return now_utc()

    metadata_path = project_dir / ".ai-docs" / "metadata.json"
    if metadata_path.exists():
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8", errors="ignore"))
            value = metadata.get("generated_at")
            if isinstance(value, str) and value.strip():
                return value.strip()
        except Exception:
            pass

    return now_utc()


def resolve_output_path(project_dir: Path, path_value: str) -> Path:
    candidate = Path(path_value).expanduser()
    if candidate.is_absolute():
        return candidate
    return (project_dir / candidate).resolve()


def build_run_metrics(
    project_dir: Path,
    mode: str,
    check_mode: bool,
    dry_run: bool,
    generated_files: list[str],
    changed_files: list[str],
    start_time: float,
    ctx: dict | None = None,
) -> dict:
    duration_ms = int((time.perf_counter() - start_time) * 1000)
    compliance_files = [p for p in generated_files if p.startswith(".specs/compliance/")]
    feature_metrics = build_feature_metrics_summary(ctx or {{}}, changed_files)
    return {{
        "timestamp": now_utc(),
        "generator_version": GENERATOR_VERSION,
        "project": str(project_dir),
        "mode": mode,
        "check_mode": bool(check_mode),
        "dry_run": bool(dry_run),
        "duration_ms": max(0, duration_ms),
        "managed_files": len(generated_files),
        "changed_files": len(changed_files),
        "compliance_files": len(compliance_files),
        "feature_metrics": feature_metrics,
    }}


def build_feature_metrics_summary(ctx: dict, changed_files: list[str]) -> dict:
    raw_metrics = ctx.get("feature_metrics", {{}}) if isinstance(ctx, dict) else {{}}
    feature_outputs = raw_metrics.get("outputs", {{}})
    feature_durations = raw_metrics.get("durations_ms", {{}})
    changed_set = set(changed_files)
    summary = {{}}

    all_names = sorted(set(feature_outputs.keys()) | set(feature_durations.keys()))
    for feature_name in all_names:
        outputs = list(feature_outputs.get(feature_name, []))
        summary[feature_name] = {{
            "generated_files": len(outputs),
            "changed_files": sum(1 for path in outputs if path in changed_set),
            "duration_ms": int(feature_durations.get(feature_name, 0)),
        }}

    return summary


def summarize_slowest_features(feature_metrics: dict, limit: int = 3) -> list[dict]:
    ranked = []
    for feature_name, payload in (feature_metrics or {{}}).items():
        ranked.append({{
            "feature": feature_name,
            "duration_ms": int(payload.get("duration_ms", 0)),
            "generated_files": int(payload.get("generated_files", 0)),
        }})

    ranked.sort(key=lambda item: (-item["duration_ms"], item["feature"]))
    return ranked[: max(1, limit)]


def write_json_report(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def update_performance_history(
    history_path: Path,
    metrics: dict,
    window_size: int = 10,
) -> dict:
    history_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        raw = json.loads(history_path.read_text(encoding="utf-8"))
    except Exception:
        raw = {{"runs": []}}

    runs = raw.get("runs", []) if isinstance(raw, dict) else []
    if not isinstance(runs, list):
        runs = []

    entry = {{
        "timestamp": metrics.get("timestamp", now_utc()),
        "duration_ms": int(metrics.get("duration_ms", 0)),
        "mode": metrics.get("mode", "unknown"),
        "changed_files": int(metrics.get("changed_files", 0)),
        "slowest_features": summarize_slowest_features(metrics.get("feature_metrics", {{}})),
    }}
    runs.append(entry)
    runs = runs[-200:]

    previous = [int(item.get("duration_ms", 0)) for item in runs[:-1] if int(item.get("duration_ms", 0)) > 0]
    previous = previous[-max(1, window_size):]
    baseline = int(sum(previous) / len(previous)) if previous else None
    regression = bool(baseline and entry["duration_ms"] > int(baseline * 1.2))

    payload = {{"runs": runs}}
    history_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    return {{
        "baseline_duration_ms": baseline,
        "current_duration_ms": entry["duration_ms"],
        "regression": regression,
        "slowest_features": entry["slowest_features"],
    }}


def resolve_compliance_packs(app_intent_input: str, selected_keys: list[str] | None = None) -> list[dict]:
    selected = merge_unique([], selected_keys or [])
    low = (app_intent_input or "").lower()

    for pack_key, pack in COMPLIANCE_PACKS.items():
        trigger_words = pack.get("trigger_keywords", [])
        if any(word in low for word in trigger_words):
            selected = merge_unique(selected, [pack_key])

    resolved = []
    for key in selected:
        pack = COMPLIANCE_PACKS.get(key)
        if not pack:
            continue
        resolved.append({{
            "key": key,
            "name": pack.get("name", key.upper()),
            "checks": pack.get("checks", []),
        }})

    return resolved


def resolve_package_guidance(stack: dict) -> dict:
    frameworks = stack.get("frameworks", []) or []
    package_managers = stack.get("package_managers", []) or []

    recommended = []
    avoid = []
    matched_profiles = []

    for framework in frameworks:
        profile = PACKAGE_GUIDANCE.get(framework)
        if not profile:
            continue
        matched_profiles.append(framework)
        recommended = merge_unique(recommended, profile.get("recommended", []))
        avoid = merge_unique(avoid, profile.get("avoid", []))

    # Language-level fallbacks when no framework profile matched.
    languages = {{item.lower() for item in (stack.get("languages", []) or [])}}
    if not matched_profiles:
        if "python" in languages:
            recommended = merge_unique(recommended, ["ruff", "mypy", "pytest", "pip-audit"])
            avoid = merge_unique(avoid, ["unmaintained python deps without recent releases"])
        if "typescript" in languages or "javascript" in languages:
            recommended = merge_unique(recommended, ["zod", "eslint", "prettier", "vitest"])
            avoid = merge_unique(avoid, ["request -> use native fetch/undici", "moment -> prefer date-fns/dayjs"])
        if "php" in languages:
            recommended = merge_unique(recommended, ["phpstan/larastan", "php-cs-fixer"])
            avoid = merge_unique(avoid, ["abandoned composer packages"])

    audit_commands = []
    for pm in package_managers:
        audit_commands = merge_unique(audit_commands, SECURITY_AUDIT_COMMANDS.get(pm, []))

    if not audit_commands:
        audit_commands = ["Run ecosystem-specific vulnerability scanning before introducing new dependencies."]

    return {{
        "matched_profiles": matched_profiles,
        "recommended_packages": recommended,
        "avoid_packages": avoid,
        "audit_commands": audit_commands,
    }}


def compute_framework_intent_bonus(stack: dict | None) -> dict[str, int]:
    bonuses = {{}}
    if not stack:
        return bonuses

    for framework in (stack.get("frameworks", []) or []):
        hint = FRAMEWORK_INTENT_HINTS.get(framework, {{}})
        for label, value in hint.items():
            bonuses[label] = bonuses.get(label, 0) + int(value)
    return bonuses


def keyword_confidence_score(raw: str, keyword: str) -> tuple[int, bool]:
    text = raw.lower()
    k = keyword.lower()
    if not k:
        return 0, False

    # Prefer explicit phrase or whole-word hits over loose substring matches.
    whole_word = re.search(rf"\\b{{re.escape(k)}}\\b", text) is not None
    if whole_word:
        return 3, True
    if k in text:
        return 1, True
    return 0, False


def resolve_app_blueprint(app_intent_input: str | None, stack: dict | None = None) -> tuple[str, str, dict]:
    raw = (app_intent_input or "").strip()
    if not raw:
        raw = "general-app"

    key = slugify_intent_key(raw)
    known = APP_ARCHETYPES.get(key)
    framework_bonus = compute_framework_intent_bonus(stack)
    if known:
        known_blueprint = dict(known)
        label = known.get("label", key)
        known_blueprint["intent_ranking"] = [{{
            "label": label,
            "score": 100 + framework_bonus.get(label, 0),
            "base_score": 100,
            "framework_bonus": framework_bonus.get(label, 0),
            "matched_keywords": [key],
        }}]
        return key, raw, known_blueprint

    base = APP_ARCHETYPES["general-app"]
    capabilities = list(base.get("capabilities", []))
    suggestions = list(base.get("suggestions", []))
    label = raw.title()
    matched = False
    ranked_matches = []
    low = raw.lower()

    for keywords, blueprint in INTENT_KEYWORD_BLUEPRINTS:
        hit_keywords = []
        score = 0
        for word in keywords:
            points, matched = keyword_confidence_score(low, word)
            if matched:
                hit_keywords.append(word)
                score += points
        if score > 0:
            matched = True
            resolved_label = blueprint.get("label", "Custom Profile")
            bonus = framework_bonus.get(resolved_label, 0)
            ranked_matches.append({{
                "label": resolved_label,
                "score": score + bonus,
                "base_score": score,
                "framework_bonus": bonus,
                "matched_keywords": hit_keywords,
            }})
            capabilities = merge_unique(capabilities, blueprint.get("capabilities", []))
            suggestions = merge_unique(suggestions, blueprint.get("suggestions", []))

    if ranked_matches:
        ranked_matches = sorted(
            ranked_matches,
            key=lambda item: (
                -item["score"],
                -item.get("framework_bonus", 0),
                -len(item.get("matched_keywords", [])),
                item["label"].lower(),
            ),
        )
        unique_labels = []
        seen = set()
        for item in ranked_matches:
            label_key = item["label"].lower().strip()
            if not label_key or label_key in seen:
                continue
            seen.add(label_key)
            unique_labels.append(item["label"])
        label = " + ".join(unique_labels)

    if matched:
        description = f"Custom app intent '{{raw}}' matched known patterns and merged targeted guidance."
    else:
        description = f"Custom app intent '{{raw}}' with generalized engineering defaults."

    custom = {{
        "label": label,
        "description": description,
        "capabilities": capabilities,
        "suggestions": suggestions,
        "intent_ranking": ranked_matches,
    }}
    return key, raw, custom


def build_common_context(project_type: str, stack: dict, new_details: dict | None, generated_at: str) -> dict:
    agents = list(DEFAULT_AGENTS)
    target_os = GENERATOR_TARGET_OS if GENERATOR_TARGET_OS != "auto" else "auto"
    locale = "en"
    compliance_region = ""
    app_intent_input = "general-app"
    compliance_keys = []
    compliance_level = 1
    custom_frameworks = []
    custom_compliance_rules = []
    custom_feature_templates = []

    if new_details:
        agents = new_details.get("agents") or agents
        target_os = new_details.get("target_os") or target_os
        locale = (new_details.get("locale") or locale).strip().lower()
        compliance_region = (new_details.get("compliance_region") or compliance_region).strip().lower()
        app_intent_input = new_details.get("app_intent_input") or new_details.get("app_intent") or app_intent_input
        compliance_keys = new_details.get("compliance_keys") or []
        compliance_level = new_details.get("compliance_level", 1)
        custom_frameworks = new_details.get("custom_frameworks") or []
        custom_compliance_rules = new_details.get("custom_compliance_rules") or []
        custom_feature_templates = new_details.get("custom_feature_templates") or []

    effective_stack = dict(stack)
    effective_stack["frameworks"] = sorted(
        set((stack.get("frameworks") or []) + custom_frameworks)
    )

    app_intent, app_intent_display, app_blueprint = resolve_app_blueprint(app_intent_input, effective_stack)
    compliance_packs = resolve_compliance_packs(app_intent_display, compliance_keys)
    if custom_compliance_rules:
        compliance_packs.extend(custom_compliance_rules)
    package_guidance = resolve_package_guidance(effective_stack)

    return {{
        "project_type": project_type,
        "target_os": target_os,
        "locale": locale,
        "compliance_region": compliance_region,
        "app_intent": app_intent,
        "app_intent_input": app_intent_display,
        "app_blueprint": app_blueprint,
        "compliance_packs": compliance_packs,
        "compliance_level": compliance_level,
        "custom_frameworks": custom_frameworks,
        "custom_compliance_rules": custom_compliance_rules,
        "custom_feature_templates": custom_feature_templates,
        "package_guidance": package_guidance,
        "agents": agents,
        "stack": effective_stack,
        "new_details": new_details or {{}},
        "generated_at": generated_at,
    }}



{gen_functions_setup}


def generate_files(project_dir: Path, ctx: dict, markdown_context: list[dict], check_mode: bool = False) -> tuple[list[str], list[str]]:
    generated = []
    changed_files = []
    active_features = set(ctx.get("active_features") or default_active_features())
    feature_outputs = {{}}
    feature_durations_ms = {{}}

    def track_feature_outputs(feature_name: str, paths: list[str] | set[str]) -> None:
        if not paths:
            return
        bucket = feature_outputs.setdefault(feature_name, set())
        bucket.update(paths)

    def add_feature_duration(feature_name: str, started_at: float) -> None:
        elapsed = int((time.perf_counter() - started_at) * 1000)
        feature_durations_ms[feature_name] = feature_durations_ms.get(feature_name, 0) + max(0, elapsed)

    base_docs_started_at = time.perf_counter()
    common_files = {{
        "AGENTS.md": generate_agents_md(ctx),
        ".ai-docs/APP-BLUEPRINT.md": generate_app_blueprint_md(ctx),
        ".ai-docs/CONTEXT-SNAPSHOT.md": generate_context_snapshot(ctx, markdown_context),


        ".ai-docs/MASTER_PROMPT_REFERENCE.md": MASTER_PROMPT,
        ".ai-docs/TOKEN-EFFICIENCY.md": """# Token Efficiency Guide

    ## Objectives
    - Minimize token usage while keeping high-signal context.
    - Keep generation deterministic and focused.

    ## Rules
    1. Read manifests and key docs first, then expand only if needed.
    2. Prefer summaries over full-file dumps for large files.
    3. Centralize shared rules in AGENTS.md and link from agent-specific docs.
    4. Avoid duplicate instructions across files.

    ## Prompt Compression Pattern
    - Context snapshot
    - Constraints
    - Acceptance criteria
    - Minimal examples
    """,
        ".ai-docs/MEMORY-MANAGEMENT.md": """# Memory Management Guide

    ## Purpose
    Define how project memory is captured and maintained for durable agent behavior.

    ## Memory Layers
    - **Global/canonical**: AGENTS.md and AI_DOCS_INDEX.md
    - **Project operational memory**: .ai-docs/*.md
    - **Feature memory**: .specs/features/<feature>/memory.md

    ## Three-Layer Memory Strategy

    ### 1. Key-Value Store (Fast Lookup)
    Store frequently accessed facts as simple key-value pairs:
    ```json
    {{
      "project_name": "MyApp",
      "primary_language": "TypeScript",
      "primary_framework": "Next.js",
      "main_db": "PostgreSQL",
      "critical_paths": ["auth", "payments", "notifications"]
    }}
    ```
    **Cost**: Single LLM call per update, instant retrieval.

    ### 2. Selective Graph (Structured Context)
    Keep relationships between concepts lightweight:
    - Current feature specs and their status
    - Known bugs and their root causes
    - Decision history for this feature
    - Related docs and memories

    Update only edges that changed this session.

    ### 3. Session Memory (Learnings)
    Record what happened this session:
    - Attempted changes and outcomes
    - New patterns discovered
    - Failures and their root causes
    - Insights for next session

    ## Operating Rules
    1. Keep memory files concise and decision-focused.
    2. Record assumptions, decisions, and unresolved questions.
    3. Update feature memory whenever feature specs or behavior changes.
    4. Archive stale decisions rather than deleting rationale.

    ## Update Strategy
    1. **Identify what changed**: Feature added? Bug fixed? Architecture shift?
    2. **Update key-value store**: Simple facts only (3-5 LLM calls max)
    3. **Update relevant graph edges**: Only touch affected relationships
    4. **Record session memory**: One structured entry with outcomes
    5. **Skip full re-extraction**: Keep old context unless invalidated

    ## Efficiency Gains
    - Instead of 20 LLM calls to re-extract everything → 3-5 calls to update what changed
    - Fast lookup of facts (key-value) vs regenerating on every query
    - Session memory acts as delta, not full recompute
    - Over time, context is progressively refined, not reset

    ## When to Refresh Fully
    Only refresh full context if:
    - Project structure fundamentally changed (new monorepo, major refactor)
    - Core tech stack changed
    - You notice selective updates are accumulating errors
    """,
        ".ai-docs/CODE-GENERATION-STANDARDS.md": """# Code Generation Standards

    ## Quality
    - Prefer readable, modular, and testable code.
    - Keep diffs small and behavior-focused.
    - Add or update tests for behavior changes.

    ## Security
    - Validate untrusted input at boundaries.
    - Avoid secrets in source, docs, and logs.
    - Use least-privilege defaults and explicit error handling.

    ## Performance
    - Avoid unnecessary allocations and repeated scans.
    - Profile critical paths before optimizing.
    - Document known tradeoffs and complexity hotspots.

    ## Definition of Done
    - Build/lint/tests pass.
    - Security checks are satisfied.
    - Relevant docs/specs/memory are updated.
    """,
        ".ai-docs/EXECUTABLE-SPECS.md": """---
title: Executable Specs Guide
type: spec-patterns
tags: [ai-docs, specs, validation]
---

# Executable Specs

Turn prompts into executable specifications that guide and validate implementation.

## Pattern
1. Start with a clear prompt or requirement.
2. Extract acceptance criteria and define inputs/outputs.
3. Write assertions that verify correctness (beyond unit tests).
4. Implement minimal code to satisfy assertions.
5. Use specs as living documentation.

## Spec Structure
```
## Requirement
<prompt or user story>

## Inputs
<expected input types and constraints>

## Outputs
<expected output types and constraints>

## Acceptance Criteria
1. ...
2. ...

## Assertions
- Assertion 1: <validates behavior X>
- Assertion 2: <validates behavior Y>

## Test Cases
- Case 1: input=..., expected_output=...
- Case 2: input=..., expected_output=...
```

## Validation Rules
- Every assertion must be tied to an acceptance criterion.
- Assertions should catch bugs that unit tests miss (edge cases, invariants).
- Specs should be executable or easily testable.
""",
        ".ai-docs/CODE-VALIDATION.md": """---
title: Code Validation Strategy
type: spec-patterns
tags: [ai-docs, validation, correctness]
---

# Code Validation

Validate code correctness beyond unit tests.

## Validation Levels
1. **Unit Tests**: Individual function/method behavior.
2. **Integration Tests**: Component interactions and workflows.
3. **Property Tests**: Invariants that should always hold.
4. **Specification Tests**: Assertions from executable specs.
5. **Scenario Tests**: Real-world user workflows end-to-end.

## Correctness Checks
- Boundary conditions (empty inputs, max/min values).
- Error handling and recovery paths.
- State consistency across operations.
- Concurrency and race conditions (if applicable).
- Resource cleanup and memory leaks.

## Spec-Driven Validation
- Define what correctness means in executable specs.
- Use specs to generate test cases automatically.
- Track validation gaps in feature memory.
- Iterate on specs when validation reveals issues.
""",
        ".ai-docs/PARALLEL-AGENTS.md": """---
title: Parallel Agents & Session Learning
type: spec-patterns
tags: [ai-docs, agents, learning]
---

# Parallel Agents & Session Learning

Enable multiple agents to work in parallel and learn from every session.

## Agent Coordination
1. **Shared Specs**: All agents read from the same executable specs.
2. **Work Partitioning**: Divide work by feature, module, or layer.
3. **Async Checkpoint**: Agents save progress to shared memory at key points.
4. **Conflict Resolution**: Use specs and acceptance criteria as the source of truth.

## Session-Based Learning
After each coding session, record:
- What was attempted and why.
- What succeeded and what failed.
- Patterns that emerged (positive and negative).
- Insights for future sessions.

## Memory Structure
```
## Session Memory
- Date & agents involved
- Features/tasks attempted
- Key decisions and trade-offs
- Bugs found and root causes
- Performance observations
- Lessons for next session
```

## Continuous Improvement
- Review session memory before starting new work.
- Update specs based on validation failures.
- Share learnings across agents via memory notes.
- Track validation improvement over time.
""",
        ".ai-docs/KNOWLEDGE-VAULT.md": """---
    title: Knowledge Vault Guide
type: knowledge-map
    tags: [ai-docs, knowledge-graph, memory, specs]
---

    # Knowledge Vault Guide

    Use this project as a markdown-first knowledge vault.

## Entry Points
- [[AI_DOCS_INDEX.md]]
- [[.ai-docs/APP-BLUEPRINT.md]]
- [[.specs/memory.md]]

## Conventions
1. Keep YAML frontmatter in notes for type/tags.
2. Prefer wiki links between related docs.
3. Keep decisions in memory notes and acceptance criteria in spec notes.
4. Update links when creating/renaming feature notes.

## Recommended Views
- Graph view filtered by tag `knowledge-graph`
- Backlinks panel for feature notes
- Search filters: `tag:specs`, `tag:memory`, `tag:ai-docs`
""",
        ".specs/README.md": """# Specs Workspace

    This folder stores spec-driven development artifacts.

    ## Structure
    - .specs/features/<feature>/spec.md
    - .specs/features/<feature>/memory.md

    ## Workflow
    1. Create or update feature spec before implementation.
    2. Maintain feature memory with decisions and open questions.
    3. Map acceptance criteria to tests.
    4. Keep specs in sync with shipped behavior.

    ## Knowledge Graph Tips
    - Keep links between `spec.md` and `memory.md` in each feature folder.
    - Use wiki links from active tasks to feature specs.
    - Use tags in frontmatter for filtering and graphing.
    """,
        ".specs/features/core/spec.md": """---
title: Feature Spec Core
type: feature-spec
tags: [ai-docs, specs, knowledge-graph]
related:
  - [[.specs/memory.md]]
  - [[.specs/features/core/memory.md]]
---

# Feature Spec: Core

    ## Goal
    Define baseline project behavior and constraints.

    ## Acceptance Criteria
    1. Documentation generation runs successfully.
    2. Generated docs are deterministic under --check mode.
    3. Security and performance standards are enforced in guidance.

    ## Test Mapping
    - AC1 -> smoke generation run
    - AC2 -> freshness check run
    - AC3 -> doc content validation

    ## Linked Notes
    - [[.specs/memory.md]]
    - [[.specs/features/core/memory.md]]
    """,
        ".specs/features/core/memory.md": """---
title: Feature Memory Core
type: feature-memory
    tags: [ai-docs, memory, knowledge-graph]
related:
  - [[.specs/memory.md]]
  - [[.specs/features/core/spec.md]]
---

# Feature Memory: Core

    ## Decisions
    - Keep check mode deterministic via metadata timestamp reuse.
    - Preserve user custom blocks during regeneration.

    ## Open Questions
    - Should feature specs be auto-created from source folders?
    - Should stale-spec detection be enforced in CI?

    ## Linked Notes
    - [[.specs/memory.md]]
    - [[.specs/features/core/spec.md]]
    """,
    }}
    add_feature_duration("base-docs", base_docs_started_at)

    if "base-docs" not in active_features:
        common_files = {{}}
    else:
        track_feature_outputs("base-docs", set(common_files.keys()))

    if "feature-catalog" in active_features:
        feature_catalog_started_at = time.perf_counter()
        common_files[".ai-docs/FEATURES.md"] = generate_feature_status_md(sorted(active_features))
        add_feature_duration("feature-catalog", feature_catalog_started_at)
        track_feature_outputs("feature-catalog", [".ai-docs/FEATURES.md"])

    if "containerization-docs" in active_features:
        containerization_started_at = time.perf_counter()
        common_files[".ai-docs/CONTAINERIZATION.md"] = generate_containerization_md(ctx)
        add_feature_duration("containerization-docs", containerization_started_at)
        track_feature_outputs("containerization-docs", [".ai-docs/CONTAINERIZATION.md"])

    if "feature-specs" in active_features:
        feature_specs_started_at = time.perf_counter()
        feature_names = detect_feature_names(project_dir)
        feature_files, specs_memory_index = build_feature_spec_files(
            feature_names, locale=ctx.get("locale", "en")
        )
        common_files[".specs/memory.md"] = specs_memory_index
        common_files.update(feature_files)
        add_feature_duration("feature-specs", feature_specs_started_at)
        track_feature_outputs("feature-specs", [".specs/memory.md", *feature_files.keys()])

    custom_feature_templates = ctx.get("custom_feature_templates", []) or []
    if "feature-specs" in active_features:
        custom_template_paths = []
        custom_templates_started_at = time.perf_counter()
        for template in custom_feature_templates:
            template_name = sanitize_feature_name(str(template.get("name") or "custom-feature"))
            template_body = str(template.get("template") or "").strip()
            if not template_body:
                continue
            template_path = f".specs/features/{{template_name}}/spec.md"
            common_files[template_path] = template_body
            custom_template_paths.append(template_path)
        add_feature_duration("feature-specs", custom_templates_started_at)
        track_feature_outputs("feature-specs", custom_template_paths)

    custom_frameworks = ctx.get("custom_frameworks", []) or []
    custom_compliance_rules = ctx.get("custom_compliance_rules", []) or []
    if "custom-agent-config" in active_features and (custom_frameworks or custom_compliance_rules or custom_feature_templates):
        custom_agent_started_at = time.perf_counter()
        framework_lines = "\\n".join(f"- {{item}}" for item in custom_frameworks) if custom_frameworks else "- (none)"
        compliance_lines = []
        for rule in custom_compliance_rules:
            compliance_lines.append(f"- {{rule.get('name', rule.get('key', 'custom-rule'))}} ({{rule.get('key', 'custom-rule')}})")
            for check in rule.get("checks", []):
                compliance_lines.append(f"  - {{check}}")
        compliance_text = "\\n".join(compliance_lines) if compliance_lines else "- (none)"
        template_lines = (
            "\\n".join(f"- .specs/features/{{sanitize_feature_name(str(item.get('name') or 'custom-feature'))}}/spec.md" for item in custom_feature_templates)
            if custom_feature_templates
            else "- (none)"
        )
        common_files[".ai-docs/CUSTOM-AGENT-CONFIG.md"] = f"""# Custom Agent Configuration

## Custom Frameworks
{{framework_lines}}

## Custom Compliance Rules
{{compliance_text}}

## Custom Feature Templates
{{template_lines}}
"""
        add_feature_duration("custom-agent-config", custom_agent_started_at)
        track_feature_outputs("custom-agent-config", [".ai-docs/CUSTOM-AGENT-CONFIG.md"])

    # Add Level 2 compliance scanning rules if configured
    compliance_level = ctx.get("compliance_level", 1)
    compliance_packs = ctx.get("compliance_packs", [])
    locale = ctx.get("locale", "en")
    compliance_region = ctx.get("compliance_region", "")
    if "compliance-level-2" in active_features and compliance_level >= 2 and compliance_packs:
        level_2_started_at = time.perf_counter()
        level_2_files = generate_level_2_compliance_scanning(
            compliance_packs,
            locale=locale,
            compliance_region=compliance_region,
        )
        common_files.update(level_2_files)
        add_feature_duration("compliance-level-2", level_2_started_at)
        track_feature_outputs("compliance-level-2", level_2_files.keys())
    if "compliance-level-3" in active_features and compliance_level >= 3 and compliance_packs:
        level_3_started_at = time.perf_counter()
        level_3_files = generate_level_3_compliance_patterns(
            compliance_packs,
            locale=locale,
            compliance_region=compliance_region,
        )
        common_files.update(level_3_files)
        add_feature_duration("compliance-level-3", level_3_started_at)
        track_feature_outputs("compliance-level-3", level_3_files.keys())
        if "patch-proposals" in active_features:
            patch_proposals_started_at = time.perf_counter()
            patch_proposal_paths = []
            injection_report = generate_level_3_pattern_injection_report(
                project_dir,
                compliance_packs,
            )
            if injection_report:
                common_files[
                    ".specs/compliance/LEVEL3-CODE-PATTERN-INJECTION.md"
                ] = injection_report
                patch_proposal_paths.append(
                    ".specs/compliance/LEVEL3-CODE-PATTERN-INJECTION.md"
                )
            patch_proposals = generate_level_3_patch_proposals(
                project_dir,
                compliance_packs,
            )
            if patch_proposals:
                common_files[
                    ".specs/compliance/LEVEL3-AUTO-PATCH-PROPOSALS.md"
                ] = patch_proposals
                patch_proposal_paths.append(
                    ".specs/compliance/LEVEL3-AUTO-PATCH-PROPOSALS.md"
                )
            add_feature_duration("patch-proposals", patch_proposals_started_at)
            track_feature_outputs("patch-proposals", patch_proposal_paths)
        if "ai-analysis" in active_features:
            ai_analysis_started_at = time.perf_counter()
            ai_analysis = generate_ai_assisted_compliance_analysis(
                project_dir,
                compliance_packs,
            )
            if ai_analysis:
                common_files[
                    ".specs/compliance/AI-ASSISTED-COMPLIANCE-ANALYSIS.md"
                ] = ai_analysis
                track_feature_outputs("ai-analysis", [".specs/compliance/AI-ASSISTED-COMPLIANCE-ANALYSIS.md"])
            add_feature_duration("ai-analysis", ai_analysis_started_at)
        if ctx.get("apply_auto_patches", False) and "auto-patch-apply" in active_features:
            auto_patch_started_at = time.perf_counter()
            apply_result = apply_level_3_patch_proposals(
                project_dir,
                compliance_packs,
                patch_allowlist=ctx.get("patch_allowlist", []),
                patch_denylist=ctx.get("patch_denylist", []),
            )
            applied_report = generate_level_3_applied_patch_report(
                project_dir,
                apply_result.get("applied", []),
            )
            if applied_report:
                common_files[
                    ".specs/compliance/LEVEL3-AUTO-PATCH-RESULTS.md"
                ] = applied_report
                track_feature_outputs("auto-patch-apply", [".specs/compliance/LEVEL3-AUTO-PATCH-RESULTS.md"])
            add_feature_duration("auto-patch-apply", auto_patch_started_at)
        if "compliance-dashboard" in active_features:
            compliance_dashboard_started_at = time.perf_counter()
            compliance_dashboard = generate_compliance_dashboard_html(
                project_dir,
                compliance_packs,
                planned_output_paths=sorted(common_files.keys()),
            )
            common_files[
                ".specs/compliance/dashboard/index.html"
            ] = compliance_dashboard
            add_feature_duration("compliance-dashboard", compliance_dashboard_started_at)
            track_feature_outputs(
                "compliance-dashboard",
                [".specs/compliance/dashboard/index.html"],
            )
    agent_docs_started_at = time.perf_counter()
    agent_files = generate_agent_specific_docs(ctx) if "agent-docs" in active_features else {{}}
    add_feature_duration("agent-docs", agent_docs_started_at)
    track_feature_outputs("agent-docs", agent_files.keys())
    all_files = dict(common_files)
    all_files.update(agent_files)

    all_paths = sorted(all_files.keys())
    index_started_at = time.perf_counter()
    index_content = generate_index_md(ctx, all_paths)
    all_files["AI_DOCS_INDEX.md"] = index_content
    add_feature_duration("base-docs", index_started_at)
    track_feature_outputs("base-docs", ["AI_DOCS_INDEX.md"])

    impacted_files, stack_changed, agents_changed, prompt_changed = determine_impacted_files(
        project_dir,
        ctx,
        all_files,
        agent_files,
        check_mode,
    )

    for rel_path, content in all_files.items():
        if not check_mode and rel_path not in impacted_files:
            generated.append(rel_path)
            continue
        file_path = project_dir / rel_path
        existing_content = read_text_if_exists(file_path)
        final_content = preserve_user_custom_blocks(existing_content, content)
        if normalize_text(existing_content) != normalize_text(final_content):
            changed_files.append(rel_path)
            if not check_mode:
                write_text(file_path, final_content)
        generated.append(rel_path)

    previous = load_previous_metadata(project_dir)
    stale_candidates = sorted(
        set(previous.get("generated_files", [])) - set(all_files.keys()) - {{".ai-docs/CHANGELOG.md", ".ai-docs/metadata.json"}}
    )
    for rel_path in stale_candidates:
        if not is_managed_generated_file(rel_path):
            continue
        file_path = project_dir / rel_path
        if not file_path.exists():
            continue
        if check_mode:
            changed_files.append(rel_path)
            continue
        if agents_changed or stack_changed:
            file_path.unlink()
            changed_files.append(rel_path)

    if not check_mode and changed_files:
        append_changelog(project_dir / ".ai-docs" / "CHANGELOG.md", f"Generated/updated {{len(changed_files)}} files.")
        generated.append(".ai-docs/CHANGELOG.md")

        write_metadata_simple(project_dir, ctx, sorted(generated))
        generated.append(".ai-docs/metadata.json")

    ctx["feature_metrics"] = {{
        "outputs": {{name: sorted(paths) for name, paths in feature_outputs.items()}},
        "durations_ms": {{name: int(value) for name, value in feature_durations_ms.items()}},
    }}

    return sorted(generated), sorted(changed_files)

'''
